/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.2.0

Source Server         : 310000_FREQDB
Source Server Version : 110200
Source Host           : 192.168.201.192:1521
Source Schema         : 310000_FREQDB

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2017-05-19 14:12:30
*/


-- ----------------------------
-- Table structure for FRBT_ALLOCATION
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ALLOCATION";
CREATE TABLE "310000_FREQDB"."FRBT_ALLOCATION" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"VER_CODE" VARCHAR2(10 BYTE) NULL ,
"AREA_CODE" VARCHAR2(10 BYTE) NULL ,
"BAND_B" NUMBER(14,7) NULL ,
"BAND_E" NUMBER(14,7) NULL ,
"FN_CODE" VARCHAR2(200 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ALLOCATION" IS '频率划分表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION"."VER_CODE" IS '版本编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION"."AREA_CODE" IS '区域代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION"."BAND_B" IS '频带开始';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION"."BAND_E" IS '频带结束';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION"."FN_CODE" IS '脚注代码';

-- ----------------------------
-- Table structure for FRBT_ALLOCATION_SERVICE
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ALLOCATION_SERVICE";
CREATE TABLE "310000_FREQDB"."FRBT_ALLOCATION_SERVICE" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ALLOC_GUID" VARCHAR2(36 BYTE) NULL ,
"ISALLOCATE" VARCHAR2(8 BYTE) NULL ,
"NOTALLOC_INFO" VARCHAR2(80 BYTE) NULL ,
"SERV_CODE" VARCHAR2(10 BYTE) NULL ,
"ADDI_INFO" VARCHAR2(80 BYTE) NULL ,
"SERV_TYPE" VARCHAR2(8 BYTE) NULL ,
"FN_CODE" VARCHAR2(200 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ALLOCATION_SERVICE" IS '频率划分无线电业务配置表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION_SERVICE"."ALLOC_GUID" IS '划分GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION_SERVICE"."ISALLOCATE" IS '是否划分业务使用';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION_SERVICE"."NOTALLOC_INFO" IS '未划分状况说明';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION_SERVICE"."SERV_CODE" IS '业务代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION_SERVICE"."ADDI_INFO" IS '业务附加说明';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION_SERVICE"."SERV_TYPE" IS '业务类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOCATION_SERVICE"."FN_CODE" IS '脚注代码';

-- ----------------------------
-- Table structure for FRBT_ALLOTMENT
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ALLOTMENT";
CREATE TABLE "310000_FREQDB"."FRBT_ALLOTMENT" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"PLANS_GUID" VARCHAR2(36 BYTE) NULL ,
"ALLOT_TYPE" VARCHAR2(8 BYTE) NULL ,
"SYS_CODE" VARCHAR2(8 BYTE) NULL ,
"FREQ_TYPE" VARCHAR2(8 BYTE) NULL ,
"BAND_TYPE" VARCHAR2(8 BYTE) NULL ,
"CH_TYPE" VARCHAR2(8 BYTE) NULL ,
"FREQ_BW" NUMBER(14,7) NULL ,
"ORG_GUID" VARCHAR2(36 BYTE) NULL ,
"FILE_NO" VARCHAR2(500 BYTE) NULL ,
"ADMIN_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"EDIT_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"START_DATE" DATE NULL ,
"STOP_DATE" DATE NULL ,
"CONFIRM_DATE" DATE NULL ,
"DATA_STATUS" VARCHAR2(8 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ALLOTMENT" IS '频率分配表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."PLANS_GUID" IS '规划GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."ALLOT_TYPE" IS '分配属性';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."SYS_CODE" IS '通信系统';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."FREQ_TYPE" IS '频率配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."BAND_TYPE" IS '频段配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."CH_TYPE" IS '频道配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."FREQ_BW" IS '信道带宽';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."ORG_GUID" IS '使用单位GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."FILE_NO" IS '批文编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."ADMIN_ORG_CODE" IS '管辖无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."EDIT_ORG_CODE" IS '维护数据的无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."START_DATE" IS '施行日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."STOP_DATE" IS '废止日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."CONFIRM_DATE" IS '批准日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."DATA_STATUS" IS '数据状态';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_ALLOTMENT_AREA
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ALLOTMENT_AREA";
CREATE TABLE "310000_FREQDB"."FRBT_ALLOTMENT_AREA" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ALLOT_CUID" VARCHAR2(36 BYTE) NULL ,
"USE_AREA" VARCHAR2(8 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ALLOTMENT_AREA" IS '频率分配使用地区表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_AREA"."ALLOT_CUID" IS '分配GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_AREA"."USE_AREA" IS '使用区域代码';

-- ----------------------------
-- Table structure for FRBT_ALLOTMENT_BAND
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ALLOTMENT_BAND";
CREATE TABLE "310000_FREQDB"."FRBT_ALLOTMENT_BAND" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ALLOT_GUID" VARCHAR2(36 BYTE) NULL ,
"BAND_LB" NUMBER(14,7) NULL ,
"BAND_LE" NUMBER(14,7) NULL ,
"BAND_UB" NUMBER(14,7) NULL ,
"BAND_UE" NUMBER(14,7) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ALLOTMENT_BAND" IS '频率分配频段配置表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_BAND"."ALLOT_GUID" IS '分配GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_BAND"."BAND_LB" IS '低频段下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_BAND"."BAND_LE" IS '低频段上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_BAND"."BAND_UB" IS '高频段下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_BAND"."BAND_UE" IS '高频段上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_BAND"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_ALLOTMENT_CHANNEL
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL";
CREATE TABLE "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ALLOT_GUID" VARCHAR2(36 BYTE) NULL ,
"PLANS_CH_GUID" VARCHAR2(36 BYTE) NULL ,
"CH_LNO" VARCHAR2(40 BYTE) NULL ,
"FREQ_LC" NUMBER(14,7) NULL ,
"FREQ_LB" NUMBER(14,7) NULL ,
"FREQ_LE" NUMBER(14,7) NULL ,
"CH_UNO" VARCHAR2(50 BYTE) NULL ,
"FREQ_UC" NUMBER(14,7) NULL ,
"FREQ_UB" NUMBER(14,7) NULL ,
"FREQ_UE" NUMBER(14,7) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL" IS '频率分配频道配置表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."ALLOT_GUID" IS '分配GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."PLANS_CH_GUID" IS '规划频道GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."CH_LNO" IS '低频波道号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."FREQ_LC" IS '中心频率（低频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."FREQ_LB" IS '低频下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."FREQ_LE" IS '低频上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."CH_UNO" IS '高频波道号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."FREQ_UC" IS '中心频率（高频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."FREQ_UB" IS '高频下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."FREQ_UE" IS '高频上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_ASSIGN
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ASSIGN";
CREATE TABLE "310000_FREQDB"."FRBT_ASSIGN" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"SYS_CODE" VARCHAR2(8 BYTE) NULL ,
"ASSIGN_TYPE" VARCHAR2(8 BYTE) NULL ,
"CH_TYPE" VARCHAR2(8 BYTE) NULL ,
"ORG_GUID" VARCHAR2(36 BYTE) NULL ,
"STAT_NAME" VARCHAR2(200 BYTE) NULL ,
"AREA_CODE" VARCHAR2(6 BYTE) NULL ,
"STAT_ADDR" VARCHAR2(400 BYTE) NULL ,
"STAT_LG" NUMBER(10,7) NULL ,
"STAT_LA" NUMBER(10,7) NULL ,
"ADMIN_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"EDIT_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"FILE_NO" VARCHAR2(500 BYTE) NULL ,
"APP_CODE" VARCHAR2(14 BYTE) NULL ,
"START_DATE" DATE NULL ,
"STOP_DATE" DATE NULL ,
"CONFIRM_DATE" DATE NULL ,
"DATA_STATUS" VARCHAR2(8 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ASSIGN" IS '频率指配表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."SYS_CODE" IS '通信系统';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."ASSIGN_TYPE" IS '指配属性';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."CH_TYPE" IS '频道配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."ORG_GUID" IS '设台单位GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."STAT_NAME" IS '台站名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."AREA_CODE" IS '台站使用地区';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."STAT_ADDR" IS '台站地址';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."STAT_LG" IS '台站经度 （西经为负数 ）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."STAT_LA" IS '台站纬度 （南纬为负数 ）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."ADMIN_ORG_CODE" IS '管辖无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."EDIT_ORG_CODE" IS '维护数据的无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."FILE_NO" IS '批文编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."APP_CODE" IS '频率使用申请表编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."START_DATE" IS '施行日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."STOP_DATE" IS '废止日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."CONFIRM_DATE" IS '批准日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."DATA_STATUS" IS '数据状态';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_ASSIGN_CHANNEL
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ASSIGN_CHANNEL";
CREATE TABLE "310000_FREQDB"."FRBT_ASSIGN_CHANNEL" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ASSIGN_GUID" VARCHAR2(36 BYTE) NULL ,
"PLANS_CH_GUID" VARCHAR2(36 BYTE) NULL ,
"ALLOT_CH_GUID" VARCHAR2(36 BYTE) NULL ,
"CH_LNO" VARCHAR2(40 BYTE) NULL ,
"FREQ_LC" NUMBER(14,7) NULL ,
"FREQ_BW" NUMBER(14,7) NULL ,
"FREQ_LB" NUMBER(14,7) NULL ,
"FREQ_LE" NUMBER(14,7) NULL ,
"CH_UNO" VARCHAR2(50 BYTE) NULL ,
"FREQ_UC" NUMBER(14,7) NULL ,
"FREQ_UB" NUMBER(14,7) NULL ,
"FREQ_UE" NUMBER(14,7) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ASSIGN_CHANNEL" IS '频率指配频道配置表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."ASSIGN_GUID" IS '指配GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."PLANS_CH_GUID" IS '规划频道GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."ALLOT_CH_GUID" IS '分配频道GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."CH_LNO" IS '低频波道号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."FREQ_LC" IS '中心频率（低频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."FREQ_BW" IS '信道带宽';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."FREQ_LB" IS '低频下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."FREQ_LE" IS '低频上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."CH_UNO" IS '高频波道号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."FREQ_UC" IS '中心频率（高频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."FREQ_UB" IS '高频下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."FREQ_UE" IS '高频上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_CALLSIGN
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_CALLSIGN";
CREATE TABLE "310000_FREQDB"."FRBT_CALLSIGN" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"TYPE_CODE" VARCHAR2(20 BYTE) NULL ,
"ISDUALRANGE" VARCHAR2(8 BYTE) NULL ,
"CS_RANGE" VARCHAR2(300 BYTE) NULL ,
"CS_NUM" VARCHAR2(8 BYTE) NULL ,
"RSIGN_RANGE" VARCHAR2(300 BYTE) NULL ,
"RSIGN_NUM" NUMBER(8) NULL ,
"ALLOT_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"EDIT_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"START_DATE" DATE NULL ,
"CONFIRM_DATE" DATE NULL ,
"DATA_STATUS" VARCHAR2(8 BYTE) NULL ,
"FILE_NO" VARCHAR2(500 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_CALLSIGN" IS '呼号数据表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."TYPE_CODE" IS '呼号类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."ISDUALRANGE" IS '是否是双核配范围';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."CS_RANGE" IS '呼号核配范围';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."CS_NUM" IS '呼号核配数量';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."RSIGN_RANGE" IS '收信台后缀核配范围';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."RSIGN_NUM" IS '后缀核配数量';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."ALLOT_ORG_CODE" IS '分配主管无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."EDIT_ORG_CODE" IS '维护数据的无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."START_DATE" IS '施行日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."CONFIRM_DATE" IS '批准日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."DATA_STATUS" IS '数据状态';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."FILE_NO" IS '批文编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_CALLSIGN_AREA
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_CALLSIGN_AREA";
CREATE TABLE "310000_FREQDB"."FRBT_CALLSIGN_AREA" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"CALLSIGN_CUID" VARCHAR2(36 BYTE) NULL ,
"USE_AREA" VARCHAR2(8 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_CALLSIGN_AREA" IS '呼号使用地区表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN_AREA"."CALLSIGN_CUID" IS '呼号GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN_AREA"."USE_AREA" IS '使用区域代码';

-- ----------------------------
-- Table structure for FRBT_CALLSIGN_TYPE
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_CALLSIGN_TYPE";
CREATE TABLE "310000_FREQDB"."FRBT_CALLSIGN_TYPE" (
"TYPE_CODE" VARCHAR2(20 BYTE) NOT NULL ,
"TYPE_NAME" VARCHAR2(100 BYTE) NULL ,
"RULE_INFO" VARCHAR2(500 BYTE) NULL ,
"ISAMATEUR" VARCHAR2(1 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_CALLSIGN_TYPE" IS '无线电台呼号类型表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN_TYPE"."TYPE_CODE" IS '呼号类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN_TYPE"."TYPE_NAME" IS '类型名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN_TYPE"."RULE_INFO" IS '编码规则说明';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CALLSIGN_TYPE"."ISAMATEUR" IS '是否业余电台呼号';

-- ----------------------------
-- Table structure for FRBT_CODE_DIC
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_CODE_DIC";
CREATE TABLE "310000_FREQDB"."FRBT_CODE_DIC" (
"CO" NUMBER NOT NULL ,
"CN" VARCHAR2(8 BYTE) NULL ,
"CODE_CHI_NAME" VARCHAR2(80 BYTE) NULL ,
"CODE_DATA_TYPE" VARCHAR2(8 BYTE) NULL ,
"CODE_TYPE_CHI_NAME" VARCHAR2(80 BYTE) NULL ,
"CODE_DISCN" NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_CODE_DIC" IS '代码数据表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CODE_DIC"."CO" IS '序号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CODE_DIC"."CN" IS '代码编码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CODE_DIC"."CODE_CHI_NAME" IS '代码中文名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CODE_DIC"."CODE_DATA_TYPE" IS '代码数据表类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CODE_DIC"."CODE_TYPE_CHI_NAME" IS '代码数据表类型中文名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_CODE_DIC"."CODE_DISCN" IS '显示序号';

-- ----------------------------
-- Table structure for FRBT_COORDINATE
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_COORDINATE";
CREATE TABLE "310000_FREQDB"."FRBT_COORDINATE" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"COOR_SIGN" VARCHAR2(36 BYTE) NULL ,
"COOR_TYPE" VARCHAR2(8 BYTE) NULL ,
"COOR_ISSUE" VARCHAR2(200 BYTE) NULL ,
"COOR_ORG1" VARCHAR2(200 BYTE) NULL ,
"COOR_ORG2" VARCHAR2(200 BYTE) NULL ,
"COOR_DATE" DATE NULL ,
"COOR_AREA" VARCHAR2(200 BYTE) NULL ,
"COOR_CON" VARCHAR2(500 BYTE) NULL ,
"COOR_FILENO" VARCHAR2(500 BYTE) NULL ,
"COOR_STANDARD" VARCHAR2(500 BYTE) NULL ,
"ADMIN_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"EDIT_ORG_CODE" VARCHAR2(9 BYTE) NOT NULL ,
"DATA_STATUS" VARCHAR2(8 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_COORDINATE" IS '频率协调数据表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."COOR_SIGN" IS '频率协调标识';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."COOR_TYPE" IS '协调类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."COOR_ISSUE" IS '协调议题';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."COOR_ORG1" IS '本方协调机构';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."COOR_ORG2" IS '对方协调机构';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."COOR_DATE" IS '协调时间';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."COOR_AREA" IS '协调地点';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."COOR_CON" IS '协调结论';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."COOR_FILENO" IS '协调纪要文件';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."COOR_STANDARD" IS '参考技术标准';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."ADMIN_ORG_CODE" IS '管辖无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."EDIT_ORG_CODE" IS '维护数据的无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."DATA_STATUS" IS '数据状态';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_COORDINATE_BAND
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_COORDINATE_BAND";
CREATE TABLE "310000_FREQDB"."FRBT_COORDINATE_BAND" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"COORSYS_GUID" VARCHAR2(36 BYTE) NULL ,
"BAND_LB" NUMBER(14,7) NULL ,
"BAND_LE" NUMBER(14,7) NULL ,
"BAND_UB" NUMBER(14,7) NULL ,
"BAND_UE" NUMBER(14,7) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_COORDINATE_BAND" IS '频率协调频段数据表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_BAND"."COORSYS_GUID" IS '协调通信系统GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_BAND"."BAND_LB" IS '低频段下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_BAND"."BAND_LE" IS '低频段上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_BAND"."BAND_UB" IS '高频段下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_BAND"."BAND_UE" IS '高频段上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_BAND"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_COORDINATE_FREQ
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_COORDINATE_FREQ";
CREATE TABLE "310000_FREQDB"."FRBT_COORDINATE_FREQ" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"COORSYS_GUID" VARCHAR2(36 BYTE) NULL ,
"PLANS_CH_GUID" VARCHAR2(36 BYTE) NULL ,
"CH_LNO" VARCHAR2(40 BYTE) NULL ,
"FREQ_LC" NUMBER(14,7) NULL ,
"FREQ_LB" NUMBER(14,7) NULL ,
"FREQ_LE" NUMBER(14,7) NULL ,
"CH_UNO" VARCHAR2(50 BYTE) NULL ,
"FREQ_UC" NUMBER(14,7) NULL ,
"FREQ_UB" NUMBER(14,7) NULL ,
"FREQ_UE" NUMBER(14,7) NULL ,
"FREQ_BW" NUMBER(14,7) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_COORDINATE_FREQ" IS '频率协调频率数据表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."COORSYS_GUID" IS '协调GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."PLANS_CH_GUID" IS '规划频道GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."CH_LNO" IS '低频波道号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."FREQ_LC" IS '中心频率（低频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."FREQ_LB" IS '低频下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."FREQ_LE" IS '低频上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."CH_UNO" IS '高频波道号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."FREQ_UC" IS '中心频率（高频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."FREQ_UB" IS '高频下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."FREQ_UE" IS '高频上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."FREQ_BW" IS '必要带宽';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_FREQ"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_COORDINATE_SYSTEM
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_COORDINATE_SYSTEM";
CREATE TABLE "310000_FREQDB"."FRBT_COORDINATE_SYSTEM" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"COOR_GUID" VARCHAR2(36 BYTE) NULL ,
"SYS_CODE" VARCHAR2(8 BYTE) NULL ,
"STAT_NAME" VARCHAR2(200 BYTE) NULL ,
"STAT_ADDR" VARCHAR2(200 BYTE) NULL ,
"FREQ_TYPE" VARCHAR2(8 BYTE) NULL ,
"BAND_TYPE" VARCHAR2(8 BYTE) NULL ,
"CH_TYPE" VARCHAR2(8 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_COORDINATE_SYSTEM" IS '频率协调通信系统表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_SYSTEM"."COOR_GUID" IS '协调GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_SYSTEM"."SYS_CODE" IS '通信系统';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_SYSTEM"."STAT_NAME" IS '协调台站名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_SYSTEM"."STAT_ADDR" IS '协调台站地址';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_SYSTEM"."FREQ_TYPE" IS '频率配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_SYSTEM"."BAND_TYPE" IS '频段配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_SYSTEM"."CH_TYPE" IS '频道配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_COORDINATE_SYSTEM"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_FILE
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_FILE";
CREATE TABLE "310000_FREQDB"."FRBT_FILE" (
"FILE_NO" VARCHAR2(100 BYTE) NOT NULL ,
"FILE_TITLE" VARCHAR2(200 BYTE) NULL ,
"FILE_TYPE" VARCHAR2(8 BYTE) NULL ,
"FILE_VERSION" VARCHAR2(20 BYTE) NULL ,
"FILE_STATUS" VARCHAR2(8 BYTE) NULL ,
"POST_ORG" VARCHAR2(200 BYTE) NULL ,
"FILE_DATE" DATE NULL ,
"FILE_DETAIL" BLOB NULL ,
"FILE_INDEX" VARCHAR2(200 BYTE) NULL ,
"EDIT_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_FILE" IS '文件表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."FILE_NO" IS '文件号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."FILE_TITLE" IS '文件标题名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."FILE_TYPE" IS '文件属性';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."FILE_VERSION" IS '文件版本';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."FILE_STATUS" IS '文件状态（是否有效）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."POST_ORG" IS '发文机关名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."FILE_DATE" IS '文件时间';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."FILE_DETAIL" IS '文件内容';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."FILE_INDEX" IS '检索关键字';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."EDIT_ORG_CODE" IS '维护数据的无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FILE"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_FOOTNOTE
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_FOOTNOTE";
CREATE TABLE "310000_FREQDB"."FRBT_FOOTNOTE" (
"FN_CODE" VARCHAR2(10 BYTE) NOT NULL ,
"FN_PROPERTY" VARCHAR2(10 BYTE) NULL ,
"FN_CLASS" VARCHAR2(10 BYTE) NULL ,
"FN_CONTENT" VARCHAR2(4000 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_FOOTNOTE" IS '脚注表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FOOTNOTE"."FN_CODE" IS '脚注代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FOOTNOTE"."FN_PROPERTY" IS '脚注性质';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FOOTNOTE"."FN_CLASS" IS '脚注分类';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FOOTNOTE"."FN_CONTENT" IS '脚注内容';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_FOOTNOTE"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_ITU
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ITU";
CREATE TABLE "310000_FREQDB"."FRBT_ITU" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"SYS_CODE" VARCHAR2(8 BYTE) NULL ,
"ALLOT_SCOPE" VARCHAR2(500 BYTE) NULL ,
"FILE_NO" VARCHAR2(500 BYTE) NULL ,
"EDIT_ORG_CODE" VARCHAR2(9 BYTE) NOT NULL ,
"START_DATE" DATE NULL ,
"STOP_DATE" DATE NULL ,
"DATA_STATUS" VARCHAR2(8 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ITU" IS '国际频率分配数据表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU"."SYS_CODE" IS '通信系统';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU"."ALLOT_SCOPE" IS '频率分配范畴';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU"."FILE_NO" IS 'ITU文档编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU"."EDIT_ORG_CODE" IS '维护数据的无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU"."START_DATE" IS '施行日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU"."STOP_DATE" IS '截止日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU"."DATA_STATUS" IS '数据状态';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_ITU_AAOBSER
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ITU_AAOBSER";
CREATE TABLE "310000_FREQDB"."FRBT_ITU_AAOBSER" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ITUAA_GUID" VARCHAR2(36 BYTE) NULL ,
"FIELD_2" VARCHAR2(20 BYTE) NULL ,
"FIELD_31" VARCHAR2(50 BYTE) NULL ,
"FIELD_32" VARCHAR2(10 BYTE) NULL ,
"FIELD_4" VARCHAR2(10 BYTE) NULL ,
"FIELD_5" VARCHAR2(10 BYTE) NULL ,
"FIELD_6" NUMBER(4,2) NULL ,
"FIELD_71" VARCHAR2(10 BYTE) NULL ,
"FIELD_72A" VARCHAR2(10 BYTE) NULL ,
"FIELD_72B" NUMBER(3) NULL ,
"FIELD_72C" NUMBER(2) NULL ,
"FIELD_9" VARCHAR2(100 BYTE) NULL ,
"FIELD_9A" VARCHAR2(100 BYTE) NULL ,
"FIELD_9B" NUMBER(4) NULL ,
"FIELD_10" VARCHAR2(40 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ITU_AAOBSER" IS '国际频率分配区域说明表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."ITUAA_GUID" IS 'ITU分配区域GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_2" IS '划分的国家或地区';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_31" IS '主服务区';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_32" IS '电路的最大长度（KM）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_4" IS '业务的性质';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_5" IS '发射类别';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_6" IS '峰包功率（DBW）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_71" IS '发射天线类别';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_72A" IS '天线最大辐射方位角';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_72B" IS '天线主瓣角宽度';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_72C" IS '天线相对增益（DB）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_9" IS '计划中频道的使用时间（UTC）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_9A" IS '估计的业务量峰值小时';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_9B" IS '估计的每日业务量（分钟数）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_AAOBSER"."FIELD_10" IS '特节号/频率周报号或BRIFIC编号/数据';

-- ----------------------------
-- Table structure for FRBT_ITU_ALLOTAREA
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ITU_ALLOTAREA";
CREATE TABLE "310000_FREQDB"."FRBT_ITU_ALLOTAREA" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ITUFREQ_GUID" VARCHAR2(36 BYTE) NULL ,
"ALLOT_AREA" VARCHAR2(1000 BYTE) NULL ,
"OBSER" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ITU_ALLOTAREA" IS '国际频率分配区域表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_ALLOTAREA"."ITUFREQ_GUID" IS 'ITU频道GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_ALLOTAREA"."ALLOT_AREA" IS '分配区域';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_ALLOTAREA"."OBSER" IS '说明';

-- ----------------------------
-- Table structure for FRBT_ITU_BAND
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ITU_BAND";
CREATE TABLE "310000_FREQDB"."FRBT_ITU_BAND" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ITU_GUID" VARCHAR2(36 BYTE) NULL ,
"BAND_NAME" VARCHAR2(100 BYTE) NULL ,
"ASSIGN_STAT" VARCHAR2(200 BYTE) NULL ,
"FREQ_TYPE" VARCHAR2(8 BYTE) NULL ,
"CH_TYPE" VARCHAR2(8 BYTE) NULL ,
"CH_FORM" VARCHAR2(8 BYTE) NULL ,
"FREQ_LCNAME" VARCHAR2(30 BYTE) NULL ,
"FREQ_UCNAME" VARCHAR2(30 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ITU_BAND" IS '国际频率分配频段基本表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BAND"."ITU_GUID" IS 'ITU GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BAND"."BAND_NAME" IS '频段名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BAND"."ASSIGN_STAT" IS '适用电台类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BAND"."FREQ_TYPE" IS '频率配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BAND"."CH_TYPE" IS '频道配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BAND"."CH_FORM" IS '频道单位类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BAND"."FREQ_LCNAME" IS '中心频率（低频）称谓';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BAND"."FREQ_UCNAME" IS '中心频率（低频）称谓';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BAND"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_ITU_BANDDATA
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ITU_BANDDATA";
CREATE TABLE "310000_FREQDB"."FRBT_ITU_BANDDATA" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ITUBAND_GUID" VARCHAR2(36 BYTE) NULL ,
"BAND_LIMIT" NUMBER(14,7) NULL ,
"ASSIGN_SCOPE" VARCHAR2(512 BYTE) NULL ,
"SIGN_CODE" VARCHAR2(200 BYTE) NULL ,
"ASSIGN_FNUM" NUMBER(3) NULL ,
"FREQ_SPACING" NUMBER(14,7) NULL ,
"BAND_LB" NUMBER(14,7) NULL ,
"BAND_LE" NUMBER(14,7) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ITU_BANDDATA" IS '国际频率分配频段细分表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BANDDATA"."ITUBAND_GUID" IS 'ITU频段GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BANDDATA"."BAND_LIMIT" IS '限值';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BANDDATA"."ASSIGN_SCOPE" IS '指配范畴';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BANDDATA"."SIGN_CODE" IS '标注说明编码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BANDDATA"."ASSIGN_FNUM" IS '可支配频率数量';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BANDDATA"."FREQ_SPACING" IS '频率间隔';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BANDDATA"."BAND_LB" IS '频段下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BANDDATA"."BAND_LE" IS '频段上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_BANDDATA"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_ITU_DESCRIPTION
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ITU_DESCRIPTION";
CREATE TABLE "310000_FREQDB"."FRBT_ITU_DESCRIPTION" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ITU_GUID" VARCHAR2(36 BYTE) NULL ,
"DESC_CODE" VARCHAR2(20 BYTE) NULL ,
"DESC_DETAIL" VARCHAR2(2000 BYTE) NULL ,
"DESC_TYPE" VARCHAR2(8 BYTE) NULL ,
"SYS_CODE" VARCHAR2(8 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ITU_DESCRIPTION" IS '国际频率说明信息表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_DESCRIPTION"."ITU_GUID" IS 'ITU GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_DESCRIPTION"."DESC_CODE" IS '说明编码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_DESCRIPTION"."DESC_DETAIL" IS '说明内容';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_DESCRIPTION"."DESC_TYPE" IS '说明类别';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_DESCRIPTION"."SYS_CODE" IS '通信系统';

-- ----------------------------
-- Table structure for FRBT_ITU_FREQ
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ITU_FREQ";
CREATE TABLE "310000_FREQDB"."FRBT_ITU_FREQ" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ITUBAND_GUID" VARCHAR2(36 BYTE) NULL ,
"CH_LNO" VARCHAR2(40 BYTE) NULL ,
"FREQ_LC" NUMBER(14,7) NULL ,
"FREQ_LA" NUMBER(14,7) NULL ,
"FREQ_LB" NUMBER(14,7) NULL ,
"FREQ_LE" NUMBER(14,7) NULL ,
"CH_UNO" VARCHAR2(50 BYTE) NULL ,
"FREQ_UC" NUMBER(14,7) NULL ,
"FREQ_UA" NUMBER(14,7) NULL ,
"FREQ_UB" NUMBER(14,7) NULL ,
"FREQ_UE" NUMBER(14,7) NULL ,
"FREQ_BW" NUMBER(14,7) NULL ,
"ISCALLFREQ" VARCHAR2(8 BYTE) NULL ,
"USAGE_CODE" VARCHAR2(200 BYTE) NULL ,
"SIGN_CODE" VARCHAR2(20 BYTE) NULL ,
"USE_IS" VARCHAR2(8 BYTE) NULL ,
"USE_PSS" VARCHAR2(8 BYTE) NULL ,
"USE_PST" VARCHAR2(8 BYTE) NULL ,
"USE_PC" VARCHAR2(8 BYTE) NULL ,
"MEMO" VARCHAR2(2000 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ITU_FREQ" IS '国际频率分配频道数据表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."ITUBAND_GUID" IS 'ITU频段GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."CH_LNO" IS '低频波道号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."FREQ_LC" IS '中心频率（低频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."FREQ_LA" IS '指配频率（低频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."FREQ_LB" IS '低频下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."FREQ_LE" IS '低频上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."CH_UNO" IS '高频波道号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."FREQ_UC" IS '中心频率（高频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."FREQ_UA" IS '指配频率（高频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."FREQ_UB" IS '高频下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."FREQ_UE" IS '高频上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."FREQ_BW" IS '必要带宽';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."ISCALLFREQ" IS '是否呼叫频率';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."USAGE_CODE" IS '使用说明编码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."SIGN_CODE" IS '标注说明编码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."USE_IS" IS '可用于船舶之间';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."USE_PSS" IS '可用于港口作业及船舶移动（单频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."USE_PST" IS '可用于港口作业及船舶移动（双频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."USE_PC" IS '可用于公众通信';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FREQ"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_ITU_FSRHD
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ITU_FSRHD";
CREATE TABLE "310000_FREQDB"."FRBT_ITU_FSRHD" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ITUBAND_GUID" VARCHAR2(36 BYTE) NULL ,
"RHD_NNS" NUMBER(5) NULL ,
"RHD_NEW" NUMBER(5) NULL ,
"RHD_SNS" NUMBER(5) NULL ,
"RHD_SEW" NUMBER(5) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ITU_FSRHD" IS '国际频率共用半复用距离表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FSRHD"."ITUBAND_GUID" IS 'ITU频段GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FSRHD"."RHD_NNS" IS '北半球南北方向半复用距离';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FSRHD"."RHD_NEW" IS '北半球东西方向半复用距离';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FSRHD"."RHD_SNS" IS '南半球南北方向半复用距离';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ITU_FSRHD"."RHD_SEW" IS '南半球东西方向半复用距离';

-- ----------------------------
-- Table structure for FRBT_ORG
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_ORG";
CREATE TABLE "310000_FREQDB"."FRBT_ORG" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"ORG_NAME" VARCHAR2(80 BYTE) NULL ,
"ORG_AREA_CODE" VARCHAR2(8 BYTE) NULL ,
"ORG_SYS_CODE" VARCHAR2(8 BYTE) NULL ,
"ORG_TYPE" VARCHAR2(3 BYTE) NULL ,
"ORG_LINK_PERSON" VARCHAR2(40 BYTE) NULL ,
"ORG_SUP_CODE" VARCHAR2(9 BYTE) NULL ,
"ORG_ADDR" VARCHAR2(80 BYTE) NULL ,
"ORG_POST" VARCHAR2(6 BYTE) NULL ,
"ORG_PHONE" VARCHAR2(40 BYTE) NULL ,
"ORG_MOB_PHONE" VARCHAR2(40 BYTE) NULL ,
"ORG_FAX" VARCHAR2(40 BYTE) NULL ,
"ORG_BANK" VARCHAR2(80 BYTE) NULL ,
"ORG_ACCOUNT_NAME" VARCHAR2(80 BYTE) NULL ,
"ORG_ACCOUNT" VARCHAR2(40 BYTE) NULL ,
"ORG_WEB_SITE" VARCHAR2(80 BYTE) NULL ,
"ORG_MAIL" VARCHAR2(80 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_ORG" IS '组织机构表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_CODE" IS '组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_NAME" IS '组织机构名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_AREA_CODE" IS '地区代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_SYS_CODE" IS '系统/行业代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_TYPE" IS '单位类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_LINK_PERSON" IS '单位联系人';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_SUP_CODE" IS '上级组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_ADDR" IS '组织机构地址';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_POST" IS '组织机构邮编';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_PHONE" IS '联系电话';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_MOB_PHONE" IS '手机号码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_FAX" IS '组织机构传真';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_BANK" IS '开户银行';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_ACCOUNT_NAME" IS '账户名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_ACCOUNT" IS '银行帐号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_WEB_SITE" IS '网址';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_ORG"."ORG_MAIL" IS '电子邮箱';

-- ----------------------------
-- Table structure for FRBT_PLANS
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_PLANS";
CREATE TABLE "310000_FREQDB"."FRBT_PLANS" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"PLANS_NAME" VARCHAR2(100 BYTE) NULL ,
"SYS_CODE" VARCHAR2(8 BYTE) NULL ,
"BAND_TYPE" VARCHAR2(8 BYTE) NULL ,
"CH_TYPE" VARCHAR2(8 BYTE) NULL ,
"FREQ_LNAME" VARCHAR2(30 BYTE) NULL ,
"FREQ_UNAME" VARCHAR2(30 BYTE) NULL ,
"EDIT_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"FILE_NO" VARCHAR2(500 BYTE) NULL ,
"START_DATE" DATE NULL ,
"CONFIRM_DATE" DATE NULL ,
"DATA_STATUS" VARCHAR2(8 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_PLANS" IS '频率规划表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."PLANS_NAME" IS '规划名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."SYS_CODE" IS '通信系统';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."BAND_TYPE" IS '频段配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."CH_TYPE" IS '频道配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."FREQ_LNAME" IS '中心频率（低频）称谓';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."FREQ_UNAME" IS '中心频率（高频）称谓';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."EDIT_ORG_CODE" IS '维护数据的无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."FILE_NO" IS '批文编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."START_DATE" IS '施行日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."CONFIRM_DATE" IS '批准日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."DATA_STATUS" IS '数据状态';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_PLANS_BAND
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_PLANS_BAND";
CREATE TABLE "310000_FREQDB"."FRBT_PLANS_BAND" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"PLANS_GUID" VARCHAR2(36 BYTE) NULL ,
"BAND_LB" NUMBER(14,7) NULL ,
"BAND_LE" NUMBER(14,7) NULL ,
"BAND_UB" NUMBER(14,7) NULL ,
"BAND_UE" NUMBER(14,7) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_PLANS_BAND" IS '频率规划频段配置表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_BAND"."PLANS_GUID" IS '规划GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_BAND"."BAND_LB" IS '低段起始频率';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_BAND"."BAND_LE" IS '低段终止频率';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_BAND"."BAND_UB" IS '高段起始频率';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_BAND"."BAND_UE" IS '高段终止频率';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_BAND"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_PLANS_CHANNEL
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_PLANS_CHANNEL";
CREATE TABLE "310000_FREQDB"."FRBT_PLANS_CHANNEL" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"PLANS_GROUP_GUID" VARCHAR2(36 BYTE) NULL ,
"CH_LNO" VARCHAR2(40 BYTE) NULL ,
"FREQ_LC" NUMBER(14,7) NULL ,
"FREQ_LB" NUMBER(14,7) NULL ,
"FREQ_LE" NUMBER(14,7) NULL ,
"CH_UNO" VARCHAR2(50 BYTE) NULL ,
"FREQ_UC" NUMBER(14,7) NULL ,
"FREQ_UB" NUMBER(14,7) NULL ,
"FREQ_UE" NUMBER(14,7) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_PLANS_CHANNEL" IS '频率规划频道配置表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_CHANNEL"."PLANS_GROUP_GUID" IS '规划分组GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_CHANNEL"."CH_LNO" IS '低频波道号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_CHANNEL"."FREQ_LC" IS '中心频率（低频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_CHANNEL"."FREQ_LB" IS '低频下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_CHANNEL"."FREQ_LE" IS '低频上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_CHANNEL"."CH_UNO" IS '高频波道号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_CHANNEL"."FREQ_UC" IS '中心频率（高频）';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_CHANNEL"."FREQ_UB" IS '高频下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_CHANNEL"."FREQ_UE" IS '高频上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_CHANNEL"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_PLANS_GROUP
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_PLANS_GROUP";
CREATE TABLE "310000_FREQDB"."FRBT_PLANS_GROUP" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"PLANS_GUID" VARCHAR2(36 BYTE) NULL ,
"GROUP_NAME" VARCHAR2(100 BYTE) NULL ,
"CH_SPACING" NUMBER(14,7) NULL ,
"CH_E_BW" NUMBER(14,7) NULL ,
"CH_ER_INTERVAL" NUMBER(14,7) NULL ,
"CH_COUNT" NUMBER(4) NULL ,
"TC_INFO" VARCHAR2(400 BYTE) NULL ,
"CH_FORM" VARCHAR2(8 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_PLANS_GROUP" IS '频率规划分组表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_GROUP"."PLANS_GUID" IS '规划GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_GROUP"."GROUP_NAME" IS '规划分组名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_GROUP"."CH_SPACING" IS '频率间隔';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_GROUP"."CH_E_BW" IS '发射必要带宽';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_GROUP"."CH_ER_INTERVAL" IS '收发频率间隔';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_GROUP"."CH_COUNT" IS '信（波）道数';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_GROUP"."TC_INFO" IS '传输容量说明';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_GROUP"."CH_FORM" IS '频道单位类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_GROUP"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_PLANS_POPEDOM
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_PLANS_POPEDOM";
CREATE TABLE "310000_FREQDB"."FRBT_PLANS_POPEDOM" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ORG_CODE" VARCHAR2(10 BYTE) NULL ,
"EDIT_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"PLANS_CH_GUID" VARCHAR2(36 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_PLANS_POPEDOM" IS '频率规划指配权限表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_POPEDOM"."ORG_CODE" IS '指配无委机构代码 ';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_POPEDOM"."EDIT_ORG_CODE" IS '维护数据的无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_POPEDOM"."PLANS_CH_GUID" IS '规划频道配置GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PLANS_POPEDOM"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_PROTECT
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_PROTECT";
CREATE TABLE "310000_FREQDB"."FRBT_PROTECT" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ORG_GUID" VARCHAR2(36 BYTE) NULL ,
"SYS_CODE" VARCHAR2(8 BYTE) NULL ,
"PF_TYPE" VARCHAR2(8 BYTE) NULL ,
"ADMIN_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"EDIT_ORG_CODE" VARCHAR2(9 BYTE) NULL ,
"FILE_NO" VARCHAR2(500 BYTE) NULL ,
"START_DATE" DATE NULL ,
"STOP_DATE" DATE NULL ,
"DATA_STATUS" VARCHAR2(8 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL ,
"FREQ_PROTECT_TYPE" VARCHAR2(8 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_PROTECT" IS '重点保护频率表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."ORG_GUID" IS '使用单位GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."SYS_CODE" IS '通信系统';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."PF_TYPE" IS '保护频率配置类型';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."ADMIN_ORG_CODE" IS '管辖无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."EDIT_ORG_CODE" IS '维护数据的无委机构组织机构代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."FILE_NO" IS '批文编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."START_DATE" IS '开始保护日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."STOP_DATE" IS '截止保护日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."DATA_STATUS" IS '数据状态';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."MEMO" IS '备注';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT"."FREQ_PROTECT_TYPE" IS '频率保护类型';

-- ----------------------------
-- Table structure for FRBT_PROTECT_AREA
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_PROTECT_AREA";
CREATE TABLE "310000_FREQDB"."FRBT_PROTECT_AREA" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"PROTECT_GUID" VARCHAR2(36 BYTE) NULL ,
"USE_AREA" VARCHAR2(8 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_PROTECT_AREA" IS '重点保护频率地区表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_AREA"."PROTECT_GUID" IS '保护GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_AREA"."USE_AREA" IS '保护区域代码';

-- ----------------------------
-- Table structure for FRBT_PROTECT_BAND
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_PROTECT_BAND";
CREATE TABLE "310000_FREQDB"."FRBT_PROTECT_BAND" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"PROTECT_GUID" VARCHAR2(36 BYTE) NULL ,
"FREQ_FB" NUMBER(14,7) NULL ,
"FREQ_FE" NUMBER(14,7) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_PROTECT_BAND" IS '重点保护频带配置表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_BAND"."PROTECT_GUID" IS '保护GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_BAND"."FREQ_FB" IS '频率下限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_BAND"."FREQ_FE" IS '频率上限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_BAND"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_PROTECT_FREQ
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_PROTECT_FREQ";
CREATE TABLE "310000_FREQDB"."FRBT_PROTECT_FREQ" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"PROTECT_GUID" VARCHAR2(36 BYTE) NULL ,
"PLANS_CH_GUID" VARCHAR2(36 BYTE) NULL ,
"FREQ_C" NUMBER(14,7) NULL ,
"FREQ_BW" NUMBER(14,7) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_PROTECT_FREQ" IS '重点保护频率配置表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_FREQ"."PROTECT_GUID" IS '保护GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_FREQ"."PLANS_CH_GUID" IS '规划频道GUID';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_FREQ"."FREQ_C" IS '中心频率';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_FREQ"."FREQ_BW" IS '带宽';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_PROTECT_FREQ"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_SERVICE
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_SERVICE";
CREATE TABLE "310000_FREQDB"."FRBT_SERVICE" (
"SERV_CODE" VARCHAR2(10 BYTE) NOT NULL ,
"SERV_NAME" VARCHAR2(80 BYTE) NULL ,
"RGB_COLOR" NUMBER(12) NULL ,
"ISCUTLINE" VARCHAR2(8 BYTE) NULL ,
"SERV_PARENT" VARCHAR2(80 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_SERVICE" IS '无线电业务表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SERVICE"."SERV_CODE" IS '业务代码';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SERVICE"."SERV_NAME" IS '业务名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SERVICE"."RGB_COLOR" IS 'RGB颜色';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SERVICE"."ISCUTLINE" IS '是否显示图例';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SERVICE"."SERV_PARENT" IS '上级业务代码';

-- ----------------------------
-- Table structure for FRBT_SYSTEM
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_SYSTEM";
CREATE TABLE "310000_FREQDB"."FRBT_SYSTEM" (
"SYS_CODE" VARCHAR2(10 BYTE) NOT NULL ,
"SYS_NAME" VARCHAR2(100 BYTE) NULL ,
"SERV_CODE" VARCHAR2(10 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_SYSTEM" IS '通信业务/系统表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM"."SYS_CODE" IS '通信业务/系统编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM"."SYS_NAME" IS '通信业务/系统名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM"."SERV_CODE" IS '所属业务编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_SYSTEM_STATPRM
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_SYSTEM_STATPRM";
CREATE TABLE "310000_FREQDB"."FRBT_SYSTEM_STATPRM" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"SYS_CODE" VARCHAR2(10 BYTE) NULL ,
"EQU_TYPE" VARCHAR2(50 BYTE) NULL ,
"FREQ_MOD" VARCHAR2(100 BYTE) NULL ,
"TX_POW" VARCHAR2(400 BYTE) NULL ,
"RX_SEN" VARCHAR2(400 BYTE) NULL ,
"FREQ_BW" VARCHAR2(400 BYTE) NULL ,
"FREQ_TOL" VARCHAR2(400 BYTE) NULL ,
"FREQ_SE" VARCHAR2(400 BYTE) NULL ,
"FILE_NO" VARCHAR2(500 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_SYSTEM_STATPRM" IS '通信系统典型台站技术参数表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM_STATPRM"."SYS_CODE" IS '通信业务/系统编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM_STATPRM"."EQU_TYPE" IS '设备种类';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM_STATPRM"."FREQ_MOD" IS '调制方式';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM_STATPRM"."TX_POW" IS '发射功率';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM_STATPRM"."RX_SEN" IS '接收机灵敏度';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM_STATPRM"."FREQ_BW" IS '占用带宽';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM_STATPRM"."FREQ_TOL" IS '频率容限';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM_STATPRM"."FREQ_SE" IS '杂散发射';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM_STATPRM"."FILE_NO" IS '相关批文编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_SYSTEM_STATPRM"."MEMO" IS '备注';

-- ----------------------------
-- Table structure for FRBT_VERSION
-- ----------------------------
DROP TABLE "310000_FREQDB"."FRBT_VERSION";
CREATE TABLE "310000_FREQDB"."FRBT_VERSION" (
"VER_CODE" VARCHAR2(10 BYTE) NOT NULL ,
"VER_NAME" VARCHAR2(100 BYTE) NULL ,
"START_DATE" DATE NULL ,
"DATA_STATUS" VARCHAR2(8 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_FREQDB"."FRBT_VERSION" IS '频率划分版本表';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_VERSION"."VER_CODE" IS '版本编号';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_VERSION"."VER_NAME" IS '版本名称';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_VERSION"."START_DATE" IS '施行日期';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_VERSION"."DATA_STATUS" IS '数据状态';
COMMENT ON COLUMN "310000_FREQDB"."FRBT_VERSION"."MEMO" IS '备注';

-- ----------------------------
-- Indexes structure for table FRBT_ALLOCATION
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ALLOCATION
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOCATION" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ALLOCATION
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOCATION" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ALLOCATION_SERVICE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ALLOCATION_SERVICE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOCATION_SERVICE" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ALLOCATION_SERVICE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOCATION_SERVICE" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ALLOTMENT
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ALLOTMENT
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOTMENT" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ALLOTMENT
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOTMENT" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ALLOTMENT_AREA
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ALLOTMENT_AREA
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOTMENT_AREA" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ALLOTMENT_AREA
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOTMENT_AREA" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ALLOTMENT_BAND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ALLOTMENT_BAND
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOTMENT_BAND" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ALLOTMENT_BAND
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOTMENT_BAND" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ALLOTMENT_CHANNEL
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ALLOTMENT_CHANNEL
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ALLOTMENT_CHANNEL
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ALLOTMENT_CHANNEL" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ASSIGN
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ASSIGN
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ASSIGN" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ASSIGN
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ASSIGN" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ASSIGN_CHANNEL
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ASSIGN_CHANNEL
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ASSIGN_CHANNEL" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ASSIGN_CHANNEL
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ASSIGN_CHANNEL" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_CALLSIGN
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_CALLSIGN
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_CALLSIGN" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_CALLSIGN
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_CALLSIGN" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_CALLSIGN_AREA
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_CALLSIGN_AREA
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_CALLSIGN_AREA" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_CALLSIGN_AREA
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_CALLSIGN_AREA" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_CALLSIGN_TYPE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_CALLSIGN_TYPE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_CALLSIGN_TYPE" ADD CHECK ("TYPE_CODE" IS NOT NULL);
ALTER TABLE "310000_FREQDB"."FRBT_CALLSIGN_TYPE" ADD CHECK ("ISAMATEUR" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_CALLSIGN_TYPE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_CALLSIGN_TYPE" ADD PRIMARY KEY ("TYPE_CODE");

-- ----------------------------
-- Indexes structure for table FRBT_CODE_DIC
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_CODE_DIC
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_CODE_DIC" ADD CHECK ("CO" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_CODE_DIC
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_CODE_DIC" ADD PRIMARY KEY ("CO");

-- ----------------------------
-- Indexes structure for table FRBT_COORDINATE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_COORDINATE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_COORDINATE" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_FREQDB"."FRBT_COORDINATE" ADD CHECK ("EDIT_ORG_CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_COORDINATE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_COORDINATE" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_COORDINATE_BAND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_COORDINATE_BAND
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_COORDINATE_BAND" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_COORDINATE_BAND
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_COORDINATE_BAND" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_COORDINATE_FREQ
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_COORDINATE_FREQ
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_COORDINATE_FREQ" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_COORDINATE_FREQ
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_COORDINATE_FREQ" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_COORDINATE_SYSTEM
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_COORDINATE_SYSTEM
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_COORDINATE_SYSTEM" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_COORDINATE_SYSTEM
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_COORDINATE_SYSTEM" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_FILE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_FILE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_FILE" ADD CHECK ("FILE_NO" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_FILE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_FILE" ADD PRIMARY KEY ("FILE_NO");

-- ----------------------------
-- Indexes structure for table FRBT_FOOTNOTE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_FOOTNOTE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_FOOTNOTE" ADD CHECK ("FN_CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_FOOTNOTE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_FOOTNOTE" ADD PRIMARY KEY ("FN_CODE");

-- ----------------------------
-- Indexes structure for table FRBT_ITU
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ITU
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_FREQDB"."FRBT_ITU" ADD CHECK ("EDIT_ORG_CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ITU
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ITU_AAOBSER
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ITU_AAOBSER
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_AAOBSER" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ITU_AAOBSER
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_AAOBSER" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ITU_ALLOTAREA
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ITU_ALLOTAREA
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_ALLOTAREA" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ITU_ALLOTAREA
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_ALLOTAREA" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ITU_BAND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ITU_BAND
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_BAND" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ITU_BAND
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_BAND" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ITU_BANDDATA
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ITU_BANDDATA
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_BANDDATA" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ITU_BANDDATA
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_BANDDATA" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ITU_DESCRIPTION
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ITU_DESCRIPTION
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_DESCRIPTION" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ITU_DESCRIPTION
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_DESCRIPTION" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ITU_FREQ
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ITU_FREQ
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_FREQ" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ITU_FREQ
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_FREQ" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ITU_FSRHD
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_ITU_FSRHD
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_FSRHD" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ITU_FSRHD
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ITU_FSRHD" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_ORG
-- ----------------------------

-- ----------------------------
-- Uniques structure for table FRBT_ORG
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ORG" ADD UNIQUE ("ORG_CODE");

-- ----------------------------
-- Checks structure for table FRBT_ORG
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ORG" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_ORG
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ORG" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_PLANS
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_PLANS
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PLANS" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_PLANS
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PLANS" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_PLANS_BAND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_PLANS_BAND
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PLANS_BAND" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_PLANS_BAND
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PLANS_BAND" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_PLANS_CHANNEL
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_PLANS_CHANNEL
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PLANS_CHANNEL" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_PLANS_CHANNEL
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PLANS_CHANNEL" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_PLANS_GROUP
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_PLANS_GROUP
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PLANS_GROUP" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_PLANS_GROUP
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PLANS_GROUP" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_PLANS_POPEDOM
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_PLANS_POPEDOM
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PLANS_POPEDOM" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_PLANS_POPEDOM
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PLANS_POPEDOM" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_PROTECT
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_PROTECT
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PROTECT" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_PROTECT
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PROTECT" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_PROTECT_AREA
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_PROTECT_AREA
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PROTECT_AREA" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_PROTECT_AREA
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PROTECT_AREA" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_PROTECT_BAND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_PROTECT_BAND
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PROTECT_BAND" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_PROTECT_BAND
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PROTECT_BAND" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_PROTECT_FREQ
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_PROTECT_FREQ
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PROTECT_FREQ" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_PROTECT_FREQ
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_PROTECT_FREQ" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_SERVICE
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table FRBT_SERVICE
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_SERVICE" ADD PRIMARY KEY ("SERV_CODE");

-- ----------------------------
-- Indexes structure for table FRBT_SYSTEM
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table FRBT_SYSTEM
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_SYSTEM" ADD PRIMARY KEY ("SYS_CODE");

-- ----------------------------
-- Indexes structure for table FRBT_SYSTEM_STATPRM
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_SYSTEM_STATPRM
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_SYSTEM_STATPRM" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_SYSTEM_STATPRM
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_SYSTEM_STATPRM" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table FRBT_VERSION
-- ----------------------------

-- ----------------------------
-- Checks structure for table FRBT_VERSION
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_VERSION" ADD CHECK ("VER_CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FRBT_VERSION
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_VERSION" ADD PRIMARY KEY ("VER_CODE");

-- ----------------------------
-- Foreign Key structure for table "310000_FREQDB"."FRBT_ASSIGN_CHANNEL"
-- ----------------------------
ALTER TABLE "310000_FREQDB"."FRBT_ASSIGN_CHANNEL" ADD FOREIGN KEY ("ASSIGN_GUID") REFERENCES "310000_FREQDB"."FRBT_ASSIGN" ("GUID");
