/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.2.0

Source Server         : 310000_ARSTATDB
Source Server Version : 110200
Source Host           : 192.168.201.192:1521
Source Schema         : 310000_ARSTATDB

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2017-05-19 13:42:12
*/


-- ----------------------------
-- Table structure for AR_APPLY
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_APPLY";
CREATE TABLE "310000_ARSTATDB"."AR_APPLY" (
"APPLY_ID" VARCHAR2(36 BYTE) NOT NULL ,
"APP_CODE" VARCHAR2(20 BYTE) NOT NULL ,
"AREA_CODE" VARCHAR2(10 BYTE) NOT NULL ,
"APP_ITEM" VARCHAR2(1 BYTE) NOT NULL ,
"APP_SUBJECT" VARCHAR2(1 BYTE) NOT NULL ,
"STAT_CLASS" VARCHAR2(1 BYTE) NOT NULL ,
"SPECIAL_EXPLAIN" VARCHAR2(50 BYTE) NULL ,
"STAT_NAME" VARCHAR2(50 BYTE) NULL ,
"STAT_SCOPE" VARCHAR2(1 BYTE) NOT NULL ,
"STAT_SPECIAL" VARCHAR2(100 BYTE) NULL ,
"STAT_TYPE" VARCHAR2(1 BYTE) NULL ,
"CALLSIGN_OLD" VARCHAR2(20 BYTE) NULL ,
"LEVEL_OLD" VARCHAR2(1 BYTE) NULL ,
"OTHERINFO" VARCHAR2(300 BYTE) NULL ,
"MEMO" VARCHAR2(300 BYTE) NULL ,
"APP_DATE" DATE NOT NULL ,
"LASTMODIFY" DATE NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."APPLY_ID" IS '申请ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."APP_CODE" IS '申请表编号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."AREA_CODE" IS '管理机构代码';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."APP_ITEM" IS '申请项目';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."APP_SUBJECT" IS '申请表主体';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."STAT_CLASS" IS '台站种类';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."SPECIAL_EXPLAIN" IS '台站特殊种类描述';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."STAT_NAME" IS '台站名称';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."STAT_SCOPE" IS '拟通信范围';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."STAT_SPECIAL" IS '特殊台站说明';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."STAT_TYPE" IS '拟设台站类别';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."CALLSIGN_OLD" IS '原指配呼号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."LEVEL_OLD" IS '原操作技术能力';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."OTHERINFO" IS '其他事项说明';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."MEMO" IS '审核备注';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."APP_DATE" IS '申请时间';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_APPLY"."LASTMODIFY" IS '最后变更时间';

-- ----------------------------
-- Table structure for AR_ATTACHMENT
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_ATTACHMENT";
CREATE TABLE "310000_ARSTATDB"."AR_ATTACHMENT" (
"FILE_ID" VARCHAR2(36 BYTE) NOT NULL ,
"APPLY_ID" VARCHAR2(36 BYTE) NOT NULL ,
"FILE_TYPE" VARCHAR2(1 BYTE) NOT NULL ,
"CONTENT" BLOB NULL ,
"FILENAME" VARCHAR2(200 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_ARSTATDB"."AR_ATTACHMENT"."FILE_ID" IS '主键';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_ATTACHMENT"."APPLY_ID" IS '申请表ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_ATTACHMENT"."FILE_TYPE" IS '附件类型';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_ATTACHMENT"."CONTENT" IS '附件内容';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_ATTACHMENT"."FILENAME" IS '附件名称';

-- ----------------------------
-- Table structure for AR_CALL_SIGN
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_CALL_SIGN";
CREATE TABLE "310000_ARSTATDB"."AR_CALL_SIGN" (
"CALL_SIGN_ID" VARCHAR2(10 BYTE) NULL ,
"AREA_CODE" VARCHAR2(10 BYTE) NULL ,
"CALL_SIGN_STATUS" VARCHAR2(1 BYTE) NULL ,
"SET_TIME" DATE NULL ,
"END_TIME" DATE NULL ,
"ACTIVATE_TIME" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for AR_CERTIFICATEINFOR
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_CERTIFICATEINFOR";
CREATE TABLE "310000_ARSTATDB"."AR_CERTIFICATEINFOR" (
"GUID" VARCHAR2(40 BYTE) NOT NULL ,
"IDNUMBER" VARCHAR2(25 BYTE) NULL ,
"NAME" VARCHAR2(20 BYTE) NULL ,
"GENDER" VARCHAR2(2 BYTE) NULL ,
"BIRTHDAY" DATE NULL ,
"CALL_SIGN" VARCHAR2(15 BYTE) NULL ,
"CURRENTLEVEL" VARCHAR2(8 BYTE) NULL ,
"PASSDATE" DATE NULL ,
"EXAMNAME" VARCHAR2(200 BYTE) NULL ,
"ISSUANCEDATE" DATE NULL ,
"ISSUANCEADDR" VARCHAR2(200 BYTE) NULL ,
"OPERATNO" VARCHAR2(20 BYTE) NULL ,
"AREACODE" VARCHAR2(30 BYTE) NULL ,
"CITIESNAME" VARCHAR2(30 BYTE) NULL ,
"ADDRESS" VARCHAR2(200 BYTE) NULL ,
"POSTCODE" VARCHAR2(6 BYTE) NULL ,
"HPHONE" VARCHAR2(30 BYTE) NULL ,
"EMAIL" VARCHAR2(100 BYTE) NULL ,
"QQCODE" VARCHAR2(20 BYTE) NULL ,
"REMARK" VARCHAR2(1000 BYTE) NULL ,
"FILENAME" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_ARSTATDB"."AR_CERTIFICATEINFOR" IS '业余台站操作证书';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."IDNUMBER" IS '证件号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."NAME" IS '姓名';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."GENDER" IS '性别';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."BIRTHDAY" IS '出生日期';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."CALL_SIGN" IS '原电台呼号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."CURRENTLEVEL" IS '操作类别';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."PASSDATE" IS '通过日期';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."EXAMNAME" IS '考场名称';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."ISSUANCEDATE" IS '核发日期';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."ISSUANCEADDR" IS '核发地点';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."OPERATNO" IS '证书号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."AREACODE" IS '省市区';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."CITIESNAME" IS '地市县';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."ADDRESS" IS '具体邮寄地址';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."POSTCODE" IS '邮编';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."HPHONE" IS '电话';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."QQCODE" IS 'QQ号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."REMARK" IS '备注';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_CERTIFICATEINFOR"."FILENAME" IS '报名文件名';

-- ----------------------------
-- Table structure for AR_DIC
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_DIC";
CREATE TABLE "310000_ARSTATDB"."AR_DIC" (
"CO" NUMBER NOT NULL ,
"CN" VARCHAR2(10 BYTE) NOT NULL ,
"CODE_CHI_NAME" VARCHAR2(80 BYTE) NOT NULL ,
"CODE_DATA_TYPE" VARCHAR2(8 BYTE) NOT NULL ,
"CODE_TYPE_CHI_NAME" VARCHAR2(80 BYTE) NULL ,
"CODE_DISCN" NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_ARSTATDB"."AR_DIC"."CO" IS '序号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_DIC"."CN" IS '代码编号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_DIC"."CODE_CHI_NAME" IS '代码中文名称';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_DIC"."CODE_DATA_TYPE" IS '代码数据表类型';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_DIC"."CODE_TYPE_CHI_NAME" IS '代码数据表类型中文名称';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_DIC"."CODE_DISCN" IS '显示序号';

-- ----------------------------
-- Table structure for AR_EQU
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_EQU";
CREATE TABLE "310000_ARSTATDB"."AR_EQU" (
"EQU_ID" VARCHAR2(36 BYTE) NOT NULL ,
"SYS_ID" VARCHAR2(36 BYTE) NOT NULL ,
"EQU_MODEL" VARCHAR2(40 BYTE) NOT NULL ,
"EQU_MFRS" VARCHAR2(100 BYTE) NULL ,
"EQU_CODE" VARCHAR2(40 BYTE) NOT NULL ,
"EQU_SN" VARCHAR2(40 BYTE) NOT NULL ,
"EQU_STATUS" VARCHAR2(1 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU"."EQU_ID" IS '设备ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU"."SYS_ID" IS '台站ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU"."EQU_MODEL" IS '设备型号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU"."EQU_MFRS" IS '设备生产厂家';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU"."EQU_CODE" IS '型号核准代码';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU"."EQU_SN" IS '出厂编号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU"."EQU_STATUS" IS '设备状态';

-- ----------------------------
-- Table structure for AR_EQU_POW
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_EQU_POW";
CREATE TABLE "310000_ARSTATDB"."AR_EQU_POW" (
"INFOID" VARCHAR2(36 BYTE) NOT NULL ,
"EQU_ID" VARCHAR2(36 BYTE) NOT NULL ,
"POW_TYPE" VARCHAR2(1 BYTE) NOT NULL ,
"POW_VALUE" NUMBER(13,3) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU_POW"."INFOID" IS '信息ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU_POW"."EQU_ID" IS '设备ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU_POW"."POW_TYPE" IS '功率类型';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_EQU_POW"."POW_VALUE" IS '功率值';

-- ----------------------------
-- Table structure for AR_STATION
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_STATION";
CREATE TABLE "310000_ARSTATDB"."AR_STATION" (
"APPLY_ID" VARCHAR2(36 BYTE) NOT NULL ,
"CALL_SIGN_ID" VARCHAR2(10 BYTE) NULL ,
"AREA_CODE" VARCHAR2(10 BYTE) NOT NULL ,
"STAT_CLASS" VARCHAR2(1 BYTE) NOT NULL ,
"STAT_STATUS" VARCHAR2(1 BYTE) NOT NULL ,
"REP_FREQ_UP" NUMBER(14,7) NULL ,
"REP_FREQ_DOWN" NUMBER(14,7) NULL ,
"REP_POW" NUMBER(10,3) NULL ,
"REP_MOD" VARCHAR2(1 BYTE) NULL ,
"REP_DATA_MOD_CLASS" VARCHAR2(1 BYTE) NULL ,
"REP_REMOTER_CLASS" VARCHAR2(1 BYTE) NULL ,
"AR_MEMO" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."APPLY_ID" IS '申请ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."CALL_SIGN_ID" IS '呼号编号（呼号）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."AREA_CODE" IS '管理机构代码';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."STAT_CLASS" IS '台站种类';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."STAT_STATUS" IS '台站状态';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."REP_FREQ_UP" IS '中继台上行频率';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."REP_FREQ_DOWN" IS '中继台下行频率';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."REP_POW" IS '中继台下行功率 ';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."REP_MOD" IS '调制方式';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."REP_DATA_MOD_CLASS" IS '数字调制系统种类';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."REP_REMOTER_CLASS" IS '遥控措施种类';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION"."AR_MEMO" IS '备注';

-- ----------------------------
-- Table structure for AR_STATION_EXT
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_STATION_EXT";
CREATE TABLE "310000_ARSTATDB"."AR_STATION_EXT" (
"SYS_ID" VARCHAR2(36 BYTE) NOT NULL ,
"APPLY_ID" VARCHAR2(36 BYTE) NOT NULL ,
"STAT_SETKIND" VARCHAR2(2 BYTE) NULL ,
"SYS_NAME" VARCHAR2(20 BYTE) NULL ,
"STAT_ADDR1" VARCHAR2(20 BYTE) NULL ,
"STAT_ADDR2" VARCHAR2(20 BYTE) NULL ,
"STAT_ADDR3" VARCHAR2(20 BYTE) NULL ,
"STAT_ADDR4" VARCHAR2(50 BYTE) NULL ,
"STAT_HEIGHT" NUMBER(10,3) NULL ,
"STAT_LG" NUMBER(10,7) NULL ,
"STAT_LA" NUMBER(10,7) NULL ,
"PLATE_NUMBER" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."SYS_ID" IS '分类ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."APPLY_ID" IS '申请表ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."STAT_SETKIND" IS '电台设置方式';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."SYS_NAME" IS '分类名称';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."STAT_ADDR1" IS '固定台地址（省份）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."STAT_ADDR2" IS '固定台地址（市、区）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."STAT_ADDR3" IS '固定台地址（县）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."STAT_ADDR4" IS '固定台地址（详细）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."STAT_HEIGHT" IS '固定台天线馈电点海拔高度';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."STAT_LG" IS '地理坐标经度';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."STAT_LA" IS '地理坐标纬度';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_STATION_EXT"."PLATE_NUMBER" IS '设台车牌号';

-- ----------------------------
-- Table structure for AR_UNIT
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_UNIT";
CREATE TABLE "310000_ARSTATDB"."AR_UNIT" (
"UNIT_ID" VARCHAR2(36 BYTE) NOT NULL ,
"APPLY_ID" VARCHAR2(36 BYTE) NOT NULL ,
"UNIT_NAME" VARCHAR2(100 BYTE) NULL ,
"REG_UNIT" VARCHAR2(100 BYTE) NULL ,
"ADDRESS1" VARCHAR2(20 BYTE) NULL ,
"ADDRESS2" VARCHAR2(20 BYTE) NULL ,
"ADDRESS3" VARCHAR2(20 BYTE) NULL ,
"ADDRESS4" VARCHAR2(100 BYTE) NULL ,
"UNIT_CODE" VARCHAR2(50 BYTE) NULL ,
"UNIT_PHONE" VARCHAR2(40 BYTE) NULL ,
"UNIT_FAX" VARCHAR2(40 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."UNIT_ID" IS '设台单位ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."APPLY_ID" IS '申请ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."UNIT_NAME" IS '设台单位名称';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."REG_UNIT" IS '申请单位登记机关';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."ADDRESS1" IS '申请单位地址（省份）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."ADDRESS2" IS '申请单位地址（市、区）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."ADDRESS3" IS '申请单位地址（县）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."ADDRESS4" IS '申请单位地址（详细）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."UNIT_CODE" IS '申请单位机构代码';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."UNIT_PHONE" IS '申请单位联系电话';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_UNIT"."UNIT_FAX" IS '申请单位传真';

-- ----------------------------
-- Table structure for AR_USER
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."AR_USER";
CREATE TABLE "310000_ARSTATDB"."AR_USER" (
"USER_ID" VARCHAR2(36 BYTE) NOT NULL ,
"APPLY_ID" VARCHAR2(36 BYTE) NOT NULL ,
"USER_TYPE" VARCHAR2(1 BYTE) NOT NULL ,
"USER_NAME" VARCHAR2(50 BYTE) NOT NULL ,
"GENDER" VARCHAR2(1 BYTE) NULL ,
"IDCARD" VARCHAR2(20 BYTE) NOT NULL ,
"NATION" VARCHAR2(40 BYTE) NULL ,
"EDUCATION" VARCHAR2(20 BYTE) NULL ,
"OPERATION_LEVEL" VARCHAR2(1 BYTE) NULL ,
"LEVEL_CODE" VARCHAR2(40 BYTE) NULL ,
"SERVICE_UNIT" VARCHAR2(100 BYTE) NULL ,
"SERVICE_POST" VARCHAR2(6 BYTE) NULL ,
"ADDRESS1" VARCHAR2(20 BYTE) NULL ,
"ADDRESS2" VARCHAR2(20 BYTE) NULL ,
"ADDRESS3" VARCHAR2(20 BYTE) NULL ,
"ADDRESS4" VARCHAR2(100 BYTE) NULL ,
"ADDRESS_POST" VARCHAR2(6 BYTE) NULL ,
"CONTACT_ADDR1" VARCHAR2(20 BYTE) NULL ,
"CONTACT_ADDR2" VARCHAR2(20 BYTE) NULL ,
"CONTACT_ADDR3" VARCHAR2(20 BYTE) NULL ,
"CONTACT_ADDR4" VARCHAR2(100 BYTE) NULL ,
"CONTACT_POST" VARCHAR2(6 BYTE) NULL ,
"EMAIL" VARCHAR2(100 BYTE) NULL ,
"FAX" VARCHAR2(40 BYTE) NULL ,
"SERVICE_PHONE" VARCHAR2(40 BYTE) NULL ,
"HOME_PHONE" VARCHAR2(40 BYTE) NULL ,
"MOBILE" VARCHAR2(40 BYTE) NULL ,
"CONNECT_PHONE" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."USER_ID" IS '人员ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."APPLY_ID" IS '申请ID';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."USER_TYPE" IS '人员类别';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."USER_NAME" IS '申请人/技术负责人/单位负责人姓名';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."GENDER" IS '申请人/技术负责人/单位负责人性别';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."IDCARD" IS '申请人/技术负责人/单位负责人身份证';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."NATION" IS '申请人/技术负责人民族';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."EDUCATION" IS '申请人/技术负责人文化程度';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."OPERATION_LEVEL" IS '申请人/技术负责人操作级别';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."LEVEL_CODE" IS '申请人/技术负责人级别证编号';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."SERVICE_UNIT" IS '申请人/技术负责人服务单位';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."SERVICE_POST" IS '申请人/技术负责人服务单位邮编';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."ADDRESS1" IS '申请人/技术负责人常住地址（省份）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."ADDRESS2" IS '申请人/技术负责人常住地址（市、区）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."ADDRESS3" IS '申请人/技术负责人常住地址（县）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."ADDRESS4" IS '申请人/技术负责人常住地址（详细）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."ADDRESS_POST" IS '申请人/技术负责人常住地址邮编';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."CONTACT_ADDR1" IS '申请人/技术负责人/单位负责人联系地址（省份）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."CONTACT_ADDR2" IS '申请人/技术负责人/单位负责人联系地址（市、区）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."CONTACT_ADDR3" IS '申请人/技术负责人/单位负责人联系地址（县）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."CONTACT_ADDR4" IS '申请人/技术负责人/单位负责人联系地址（详细）';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."CONTACT_POST" IS '申请人/技术负责人/单位负责人联系地址邮编';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."EMAIL" IS '申请人/技术负责人/单位负责人电子邮件';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."FAX" IS '申请人/技术负责人/单位负责人传真';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."SERVICE_PHONE" IS '申请人/技术负责人/单位负责人单位电话';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."HOME_PHONE" IS '申请人/技术负责人/单位负责人住宅电话';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."MOBILE" IS '申请人/技术负责人/单位负责人移动电话';
COMMENT ON COLUMN "310000_ARSTATDB"."AR_USER"."CONNECT_PHONE" IS '单位负责人联系电话';

-- ----------------------------
-- Table structure for T_RIM_PA_ARCERTIFICATEINFOR
-- ----------------------------
DROP TABLE "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR";
CREATE TABLE "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR" (
"GUID" VARCHAR2(40 BYTE) NOT NULL ,
"IDNUMBER" VARCHAR2(25 BYTE) NULL ,
"NAME" VARCHAR2(20 BYTE) NULL ,
"GENDER" VARCHAR2(2 BYTE) NULL ,
"BIRTHDAY" DATE NULL ,
"CALL_SIGN" VARCHAR2(15 BYTE) NULL ,
"CURRENTLEVEL" VARCHAR2(8 BYTE) NULL ,
"PASSDATE" DATE NULL ,
"EXAMNAME" VARCHAR2(200 BYTE) NULL ,
"ISSUANCEDATE" DATE NULL ,
"ISSUANCEADDR" VARCHAR2(200 BYTE) NULL ,
"OPERATNO" VARCHAR2(20 BYTE) NULL ,
"AREACODE" VARCHAR2(30 BYTE) NULL ,
"CITIESNAME" VARCHAR2(30 BYTE) NULL ,
"ADDRESS" VARCHAR2(200 BYTE) NULL ,
"POSTCODE" VARCHAR2(6 BYTE) NULL ,
"HPHONE" VARCHAR2(30 BYTE) NULL ,
"EMAIL" VARCHAR2(100 BYTE) NULL ,
"QQCODE" VARCHAR2(20 BYTE) NULL ,
"REMARK" VARCHAR2(1000 BYTE) NULL ,
"FILENAME" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."IDNUMBER" IS '证件号';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."NAME" IS '姓名';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."GENDER" IS '性别';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."BIRTHDAY" IS '出生日期';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."CALL_SIGN" IS '原电台呼号';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."CURRENTLEVEL" IS '操作类别';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."PASSDATE" IS '通过日期';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."EXAMNAME" IS '考场名称';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."ISSUANCEDATE" IS '核发日期';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."ISSUANCEADDR" IS '核发地点';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."OPERATNO" IS '证书号';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."AREACODE" IS '省市区';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."CITIESNAME" IS '地市县';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."ADDRESS" IS '具体邮寄地址';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."POSTCODE" IS '邮编';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."HPHONE" IS '电话';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."QQCODE" IS 'QQ号';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."REMARK" IS '备注';
COMMENT ON COLUMN "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR"."FILENAME" IS '报名文件名';

-- ----------------------------
-- Indexes structure for table AR_APPLY
-- ----------------------------

-- ----------------------------
-- Triggers structure for table AR_APPLY
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_ARSTATDB"."B17PA_DELETE" BEFORE DELETE ON "310000_ARSTATDB"."AR_APPLY" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
BEGIN
 delete from ar_user u where u.apply_id = :old.apply_id;
 delete from AR_UNIT n where n.apply_id = :old.apply_id;
 delete from AR_STATION_EXT e where e.apply_id = :old.apply_id;
 delete from AR_STATION s where s.apply_id = :old.apply_id;
END;

-- ----------------------------
-- Checks structure for table AR_APPLY
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_APPLY" ADD CHECK ("APPLY_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_APPLY" ADD CHECK ("APP_CODE" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_APPLY" ADD CHECK ("AREA_CODE" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_APPLY" ADD CHECK ("APP_ITEM" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_APPLY" ADD CHECK ("APP_SUBJECT" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_APPLY" ADD CHECK ("STAT_CLASS" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_APPLY" ADD CHECK ("STAT_SCOPE" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_APPLY" ADD CHECK ("APP_DATE" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_APPLY" ADD CHECK ("LASTMODIFY" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AR_APPLY
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_APPLY" ADD PRIMARY KEY ("APPLY_ID");

-- ----------------------------
-- Indexes structure for table AR_ATTACHMENT
-- ----------------------------

-- ----------------------------
-- Checks structure for table AR_ATTACHMENT
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_ATTACHMENT" ADD CHECK ("FILE_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_ATTACHMENT" ADD CHECK ("APPLY_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_ATTACHMENT" ADD CHECK ("FILE_TYPE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AR_ATTACHMENT
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_ATTACHMENT" ADD PRIMARY KEY ("FILE_ID");

-- ----------------------------
-- Checks structure for table AR_CERTIFICATEINFOR
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_CERTIFICATEINFOR" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table AR_DIC
-- ----------------------------

-- ----------------------------
-- Checks structure for table AR_DIC
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_DIC" ADD CHECK ("CO" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_DIC" ADD CHECK ("CN" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_DIC" ADD CHECK ("CODE_CHI_NAME" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_DIC" ADD CHECK ("CODE_DATA_TYPE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AR_DIC
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_DIC" ADD PRIMARY KEY ("CO");

-- ----------------------------
-- Indexes structure for table AR_EQU
-- ----------------------------

-- ----------------------------
-- Triggers structure for table AR_EQU
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_ARSTATDB"."B17PA_DELETE_EQU_P" BEFORE DELETE ON "310000_ARSTATDB"."AR_EQU" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
BEGIN
 delete from AR_EQU_pow p where p.equ_id = :old.equ_id;
END;

-- ----------------------------
-- Checks structure for table AR_EQU
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_EQU" ADD CHECK ("EQU_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_EQU" ADD CHECK ("SYS_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_EQU" ADD CHECK ("EQU_MODEL" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_EQU" ADD CHECK ("EQU_CODE" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_EQU" ADD CHECK ("EQU_SN" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_EQU" ADD CHECK ("EQU_STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AR_EQU
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_EQU" ADD PRIMARY KEY ("EQU_ID");

-- ----------------------------
-- Indexes structure for table AR_EQU_POW
-- ----------------------------

-- ----------------------------
-- Checks structure for table AR_EQU_POW
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_EQU_POW" ADD CHECK ("INFOID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_EQU_POW" ADD CHECK ("EQU_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_EQU_POW" ADD CHECK ("POW_TYPE" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_EQU_POW" ADD CHECK ("POW_VALUE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AR_EQU_POW
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_EQU_POW" ADD PRIMARY KEY ("INFOID");

-- ----------------------------
-- Indexes structure for table AR_STATION
-- ----------------------------

-- ----------------------------
-- Checks structure for table AR_STATION
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_STATION" ADD CHECK ("APPLY_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_STATION" ADD CHECK ("AREA_CODE" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_STATION" ADD CHECK ("STAT_CLASS" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_STATION" ADD CHECK ("STAT_STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AR_STATION
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_STATION" ADD PRIMARY KEY ("APPLY_ID");

-- ----------------------------
-- Indexes structure for table AR_STATION_EXT
-- ----------------------------

-- ----------------------------
-- Triggers structure for table AR_STATION_EXT
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_ARSTATDB"."B17PA_DELETE_EQU" BEFORE DELETE ON "310000_ARSTATDB"."AR_STATION_EXT" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
BEGIN
 delete from AR_EQU u where u.sys_id = :old.sys_id;
END;

-- ----------------------------
-- Checks structure for table AR_STATION_EXT
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_STATION_EXT" ADD CHECK ("SYS_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_STATION_EXT" ADD CHECK ("APPLY_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AR_STATION_EXT
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_STATION_EXT" ADD PRIMARY KEY ("SYS_ID");

-- ----------------------------
-- Indexes structure for table AR_UNIT
-- ----------------------------

-- ----------------------------
-- Checks structure for table AR_UNIT
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_UNIT" ADD CHECK ("UNIT_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_UNIT" ADD CHECK ("APPLY_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AR_UNIT
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_UNIT" ADD PRIMARY KEY ("UNIT_ID");

-- ----------------------------
-- Indexes structure for table AR_USER
-- ----------------------------

-- ----------------------------
-- Checks structure for table AR_USER
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_USER" ADD CHECK ("USER_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_USER" ADD CHECK ("APPLY_ID" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_USER" ADD CHECK ("USER_TYPE" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_USER" ADD CHECK ("USER_NAME" IS NOT NULL);
ALTER TABLE "310000_ARSTATDB"."AR_USER" ADD CHECK ("IDCARD" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AR_USER
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_USER" ADD PRIMARY KEY ("USER_ID");

-- ----------------------------
-- Checks structure for table T_RIM_PA_ARCERTIFICATEINFOR
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."T_RIM_PA_ARCERTIFICATEINFOR" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Foreign Key structure for table "310000_ARSTATDB"."AR_ATTACHMENT"
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_ATTACHMENT" ADD FOREIGN KEY ("APPLY_ID") REFERENCES "310000_ARSTATDB"."AR_APPLY" ("APPLY_ID");

-- ----------------------------
-- Foreign Key structure for table "310000_ARSTATDB"."AR_EQU"
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_EQU" ADD FOREIGN KEY ("SYS_ID") REFERENCES "310000_ARSTATDB"."AR_STATION_EXT" ("SYS_ID");

-- ----------------------------
-- Foreign Key structure for table "310000_ARSTATDB"."AR_EQU_POW"
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_EQU_POW" ADD FOREIGN KEY ("EQU_ID") REFERENCES "310000_ARSTATDB"."AR_EQU" ("EQU_ID");

-- ----------------------------
-- Foreign Key structure for table "310000_ARSTATDB"."AR_STATION"
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_STATION" ADD FOREIGN KEY ("APPLY_ID") REFERENCES "310000_ARSTATDB"."AR_APPLY" ("APPLY_ID");

-- ----------------------------
-- Foreign Key structure for table "310000_ARSTATDB"."AR_UNIT"
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_UNIT" ADD FOREIGN KEY ("APPLY_ID") REFERENCES "310000_ARSTATDB"."AR_APPLY" ("APPLY_ID");

-- ----------------------------
-- Foreign Key structure for table "310000_ARSTATDB"."AR_USER"
-- ----------------------------
ALTER TABLE "310000_ARSTATDB"."AR_USER" ADD FOREIGN KEY ("APPLY_ID") REFERENCES "310000_ARSTATDB"."AR_APPLY" ("APPLY_ID");
