/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.2.0

Source Server         : 310000_STATDB
Source Server Version : 110200
Source Host           : 192.168.201.192:1521
Source Schema         : 310000_STATDB

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2017-05-19 13:48:13
*/


-- ----------------------------
-- Table structure for RSBT_ANTFEED
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_ANTFEED";
CREATE TABLE "310000_STATDB"."RSBT_ANTFEED" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"STATION_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ANT_WORK_TYPE" VARCHAR2(8 BYTE) NULL ,
"ANT_POLE" VARCHAR2(8 BYTE) NULL ,
"ANT_RPOLE" VARCHAR2(8 BYTE) NULL ,
"ANT_EPOLE" VARCHAR2(8 BYTE) NULL ,
"ANT_TYPE" VARCHAR2(8 BYTE) NULL ,
"ANT_MODEL" VARCHAR2(40 BYTE) NULL ,
"ANT_MENU" VARCHAR2(80 BYTE) NULL ,
"ANT_HIGHT" NUMBER(7,3) NULL ,
"ANT_GAIN" NUMBER(6,3) NULL ,
"ANT_EGAIN" NUMBER(6,3) NULL ,
"ANT_RGAIN" NUMBER(6,3) NULL ,
"ANT_ANGLE" NUMBER(7,4) NULL ,
"ANT_SIZE" VARCHAR2(20 BYTE) NULL ,
"FEED_MENU" VARCHAR2(80 BYTE) NULL ,
"FEED_MODEL" VARCHAR2(40 BYTE) NULL ,
"FEED_LENGTH" NUMBER(6,3) NULL ,
"FEED_LOSE" NUMBER(6,3) NULL ,
"ANT_CODE" NUMBER(36) NULL ,
"FEED_CODE" NUMBER(36) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_ANTFEED_T
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_ANTFEED_T";
CREATE TABLE "310000_STATDB"."RSBT_ANTFEED_T" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"AT_ANT_NO" VARCHAR2(4 BYTE) NULL ,
"AT_SE_B" NUMBER(10,7) NULL ,
"AT_SE_E" NUMBER(10,7) NULL ,
"AT_ANG_B" NUMBER(10,7) NULL ,
"AT_ANG_E" NUMBER(10,7) NULL ,
"AT_RNT" NUMBER(9,3) NULL ,
"AT_BWID" NUMBER(10,7) NULL ,
"AT_LEL" NUMBER(9,3) NULL ,
"AT_SSPEED" NUMBER(9,3) NULL ,
"AT_CCODE" VARCHAR2(20 BYTE) NULL ,
"AT_3DBE" NUMBER(10,7) NULL ,
"AT_3DBR" NUMBER(10,7) NULL ,
"AT_RANG" NUMBER(10,7) NULL ,
"AT_EANG" NUMBER(10,7) NULL ,
"AT_CSGN" VARCHAR2(20 BYTE) NULL ,
"AT_UPDN" VARCHAR2(1 BYTE) NULL ,
"AT_SUM" NUMBER(3) NULL ,
"AT_QUA" VARCHAR2(20 BYTE) NULL ,
"AT_UNIT_TYPE" VARCHAR2(8 BYTE) NULL ,
"AT_H_HPIC" VARCHAR2(80 BYTE) NULL ,
"AT_H_VPIC" VARCHAR2(80 BYTE) NULL ,
"AT_ANT_UPANG" NUMBER(10,7) NULL ,
"AT_ANT_TFCODE" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_APPCLUBS
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_APPCLUBS";
CREATE TABLE "310000_STATDB"."RSBT_APPCLUBS" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"APP_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"APP_CLUBS_NAME" VARCHAR2(80 BYTE) NULL ,
"APP_CLUBS_SUP_ORG" VARCHAR2(80 BYTE) NULL ,
"APP_CLUBS_MEMBER_CODE" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_APPFILELIST
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_APPFILELIST";
CREATE TABLE "310000_STATDB"."RSBT_APPFILELIST" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"APP_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"APP_CODE" VARCHAR2(14 BYTE) NOT NULL ,
"APP_FILE_NO" VARCHAR2(40 BYTE) NULL ,
"APP_ATTACHMENT" VARCHAR2(120 BYTE) NULL ,
"APP_FILE_URL" VARCHAR2(120 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_APPFREQ
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_APPFREQ";
CREATE TABLE "310000_STATDB"."RSBT_APPFREQ" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"APP_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"APP_CODE" VARCHAR2(14 BYTE) NOT NULL ,
"APP_FREQ_LC" NUMBER(14,7) NULL ,
"APP_FREQ_UC" NUMBER(14,7) NULL ,
"APP_FREQ_LFB" NUMBER(14,7) NULL ,
"APP_FREQ_LFE" NUMBER(14,7) NULL ,
"APP_FREQ_LB" NUMBER(14,7) NULL ,
"APP_FREQ_UFB" NUMBER(14,7) NULL ,
"APP_FREQ_UFE" NUMBER(14,7) NULL ,
"APP_FREQ_UB" NUMBER(14,7) NULL ,
"APP_FREQ_CODE" VARCHAR2(36 BYTE) NULL ,
"APP_FREQ_TYPE" VARCHAR2(1 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_APPLY
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_APPLY";
CREATE TABLE "310000_STATDB"."RSBT_APPLY" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ORG_GUID" VARCHAR2(36 BYTE) NULL ,
"NET_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ORG_MANAGER_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"APP_CODE" VARCHAR2(14 BYTE) NOT NULL ,
"APP_TYPE" VARCHAR2(8 BYTE) NOT NULL ,
"APP_SUB_TYPE" VARCHAR2(8 BYTE) NOT NULL ,
"APP_OBJECT_TYPE" VARCHAR2(8 BYTE) NOT NULL ,
"APP_DATE" DATE NULL ,
"APP_FTLB" DATE NOT NULL ,
"APP_FTLE" DATE NOT NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_APPLY_PA
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_APPLY_PA";
CREATE TABLE "310000_STATDB"."RSBT_APPLY_PA" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"APP_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"APP_PA_NAME" VARCHAR2(40 BYTE) NOT NULL ,
"APP_PA_GENDER" VARCHAR2(1 BYTE) NOT NULL ,
"APP_PA_BIRTHDAY" DATE NOT NULL ,
"APP_PA_NATION" VARCHAR2(40 BYTE) NOT NULL ,
"APP_PA_DEGREE" VARCHAR2(20 BYTE) NOT NULL ,
"APP_PA_ID_CARD" VARCHAR2(20 BYTE) NOT NULL ,
"APP_PA_SERV_ORG" VARCHAR2(80 BYTE) NULL ,
"APP_PA_SERV_POST" VARCHAR2(6 BYTE) NULL ,
"APP_PA_LIVE_ADDR" VARCHAR2(80 BYTE) NULL ,
"APP_PA_LIVE_POST" VARCHAR2(6 BYTE) NULL ,
"APP_PA_CONTACT_ADDR" VARCHAR2(80 BYTE) NULL ,
"APP_PA_CONTACT_POST" VARCHAR2(6 BYTE) NULL ,
"APP_PA_EMAIL" VARCHAR2(80 BYTE) NULL ,
"APP_PA_ORG_PHONE" VARCHAR2(40 BYTE) NULL ,
"APP_PA_HOME_PHONE" VARCHAR2(40 BYTE) NULL ,
"APP_PA_MOBILE" VARCHAR2(40 BYTE) NULL ,
"APP_PA_OTHER_INFO" VARCHAR2(512 BYTE) NULL ,
"APP_PA_STAT_TYPE" VARCHAR2(8 BYTE) NULL ,
"APP_PA_ENTITY_TYPE" VARCHAR2(1 BYTE) NULL ,
"APP_PA_STAT_ADDR" VARCHAR2(80 BYTE) NULL ,
"APP_PA_OPE_DEGREE" VARCHAR2(20 BYTE) NULL ,
"APP_PA_OPE_CODE" VARCHAR2(20 BYTE) NULL ,
"APP_PA_CALL_SIGN" VARCHAR2(20 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_CODE_DIC
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_CODE_DIC";
CREATE TABLE "310000_STATDB"."RSBT_CODE_DIC" (
"CO" NUMBER NOT NULL ,
"CN" VARCHAR2(10 BYTE) NOT NULL ,
"CODE_CHI_NAME" VARCHAR2(120 BYTE) NULL ,
"CODE_DATA_TYPE" VARCHAR2(8 BYTE) NULL ,
"CODE_TYPE_CHI_NAME" VARCHAR2(80 BYTE) NULL ,
"CODE_DISCN" NUMBER NOT NULL ,
"CODE_USE_RANGE" VARCHAR2(100 BYTE) NULL ,
"CODE1" VARCHAR2(80 BYTE) NULL ,
"IMPORT_CODE" VARCHAR2(80 BYTE) NULL ,
"IMPORT_NAME" VARCHAR2(120 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_DB_POOL
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_DB_POOL";
CREATE TABLE "310000_STATDB"."RSBT_DB_POOL" (
"ORG_AREA_CODE" VARCHAR2(8 BYTE) NOT NULL ,
"SERVER_ADRESS1" VARCHAR2(30 BYTE) NULL ,
"SERVER_ADRESS2" VARCHAR2(30 BYTE) NULL ,
"DATABASE_SERVER_NAME" VARCHAR2(20 BYTE) NULL ,
"DATABASE_NAME" VARCHAR2(30 BYTE) NULL ,
"DATABASE_MANAGEMENT_USER" VARCHAR2(20 BYTE) NOT NULL ,
"DATABASE_PASSWORD" VARCHAR2(20 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_E_SE
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_E_SE";
CREATE TABLE "310000_STATDB"."RSBT_E_SE" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"STATION_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"SE_COMM" NUMBER(7,4) NULL ,
"SE_ANGLE" NUMBER(7,4) NULL ,
"SE_DIS" NUMBER(7,4) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_EAF
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_EAF";
CREATE TABLE "310000_STATDB"."RSBT_EAF" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"STATION_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"EQU_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ANT_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"FREQ_GUID" VARCHAR2(36 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_EQU
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_EQU";
CREATE TABLE "310000_STATDB"."RSBT_EQU" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"STATION_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"EQU_TYPE" VARCHAR2(8 BYTE) NULL ,
"EQU_MODEL" VARCHAR2(40 BYTE) NULL ,
"EQU_AUTH" VARCHAR2(40 BYTE) NULL ,
"EQU_MENU" VARCHAR2(80 BYTE) NULL ,
"EQU_CODE" VARCHAR2(40 BYTE) NULL ,
"EQU_PF" VARCHAR2(8 BYTE) NULL ,
"EQU_MB" VARCHAR2(1 BYTE) NULL ,
"EQU_POW" NUMBER(14,7) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_EQU_T
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_EQU_T";
CREATE TABLE "310000_STATDB"."RSBT_EQU_T" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ET_EQU_NO" VARCHAR2(4 BYTE) NULL ,
"ET_AF_TYPE" VARCHAR2(1 BYTE) NULL ,
"ET_POW_U" VARCHAR2(8 BYTE) NULL ,
"ET_EQU_CL" VARCHAR2(20 BYTE) NULL ,
"ET_EQU_TL" NUMBER(9,3) NULL ,
"ET_EQU_RNQ" NUMBER(9,3) NULL ,
"ET_EQU_TYPE_ID" VARCHAR2(8 BYTE) NULL ,
"ET_EQU_NAME" VARCHAR2(80 BYTE) NULL ,
"ET_EQU_CODE" VARCHAR2(10 BYTE) NULL ,
"ET_EQU_ESGN" VARCHAR2(20 BYTE) NULL ,
"ET_EQU_EPOS" VARCHAR2(40 BYTE) NULL ,
"ET_EQU_ATYPE" VARCHAR2(8 BYTE) NULL ,
"ET_EQU_APOS" VARCHAR2(40 BYTE) NULL ,
"ET_EQU_SUM" NUMBER(7) NULL ,
"ET_EQU_EUSE" VARCHAR2(20 BYTE) NULL ,
"ET_EQU_FNTVAL" NUMBER(10,3) NULL ,
"ET_EQU_PUP" NUMBER(10,3) NULL ,
"ET_EQU_PDN" NUMBER(10,3) NULL ,
"ET_EQU_CHRIP" NUMBER(10,3) NULL ,
"ET_EQU_PWID1" NUMBER(10,3) NULL ,
"ET_EQU_PWID2" NUMBER(10,3) NULL ,
"ET_EQU_PR" NUMBER(10,3) NULL ,
"ET_EQU_PF" NUMBER(10,3) NULL ,
"ET_EQU_RF" NUMBER(10,3) NULL ,
"ET_EQU_RF_BAND" NUMBER(10,3) NULL ,
"ET_EIRP" NUMBER(14,7) NULL ,
"ET_EQU_SEN" NUMBER(10,3) NULL ,
"ET_EQU_SENU" VARCHAR2(8 BYTE) NULL ,
"ET_EQU_SENERR" VARCHAR2(10 BYTE) NULL ,
"ET_EQU_RWID" NUMBER(14,7) NULL ,
"ET_EQU_MT" VARCHAR2(8 BYTE) NULL ,
"ET_EQU_CCODE" VARCHAR2(20 BYTE) NULL ,
"ET_EQU_UPU" VARCHAR2(8 BYTE) NULL ,
"ET_EQU_DNU" VARCHAR2(8 BYTE) NULL ,
"ET_EQU_TYPE" VARCHAR2(20 BYTE) NULL ,
"ET_EQU_USE" VARCHAR2(40 BYTE) NULL ,
"ET_EQU_UPOW" NUMBER(14,7) NULL ,
"ET_EQU_DPOW" NUMBER(14,7) NULL ,
"ET_EQU_POW_AVG" NUMBER(10,3) NULL ,
"ET_EQU_POW_MAX" NUMBER(10,3) NULL ,
"ET_EQU_TFCODE" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_FEE_DERATE
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_FEE_DERATE";
CREATE TABLE "310000_STATDB"."RSBT_FEE_DERATE" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"NAME" VARCHAR2(300 BYTE) NOT NULL ,
"PROPORTION" NUMBER(4,3) NOT NULL ,
"DESCRIPTION" VARCHAR2(1000 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_FEEEVERYYEAR
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR";
CREATE TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ORG_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"NET_GUID" VARCHAR2(36 BYTE) NULL ,
"STATION_GUID" VARCHAR2(36 BYTE) NULL ,
"FEE_TYPE" NUMBER(1) NOT NULL ,
"FEE_SUM" NUMBER(8,2) NOT NULL ,
"FEE_DERATE_PROPORTION" NUMBER(4,3) NULL ,
"FEE_DERATE_ACCORDING" VARCHAR2(36 BYTE) NULL ,
"FEE_START_DATE" DATE NULL ,
"FEE_END_DATE" DATE NULL ,
"FEE_PAY_MONTH" NUMBER(2) NOT NULL ,
"FEE_OPERATION" VARCHAR2(40 BYTE) NOT NULL ,
"FEE_OPERATION_DATE" DATE NOT NULL ,
"FEE_AUDIT" VARCHAR2(40 BYTE) NULL ,
"FEE_AUDIT_DATE" DATE NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_FEERECORD
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_FEERECORD";
CREATE TABLE "310000_STATDB"."RSBT_FEERECORD" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"FEE_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"FEE_TIME" DATE NOT NULL ,
"FEE_YEAR" NUMBER(4) NOT NULL ,
"FEE_SUM" NUMBER(11,2) NOT NULL ,
"FEE_LATE" NUMBER(11,2) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_FEESTANDERD
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_FEESTANDERD";
CREATE TABLE "310000_STATDB"."RSBT_FEESTANDERD" (
"ITEM_CODE" VARCHAR2(10 BYTE) NOT NULL ,
"ITEM_NAME" VARCHAR2(100 BYTE) NOT NULL ,
"ITEM_TYPE" VARCHAR2(10 BYTE) NOT NULL ,
"TYPE_NAME" VARCHAR2(30 BYTE) NOT NULL ,
"FEE_PAY" NUMBER(11,2) NOT NULL ,
"COUNT_MODE" VARCHAR2(30 BYTE) NOT NULL ,
"SET_DATE" DATE NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_FEEUNITRECORD
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_FEEUNITRECORD";
CREATE TABLE "310000_STATDB"."RSBT_FEEUNITRECORD" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ORG_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"FEE_TIME" DATE NOT NULL ,
"FEE_YEAR" NUMBER(4) NOT NULL ,
"FEE_BILL" NUMBER(11,2) NULL ,
"FEE_PAYMENT" NUMBER(11,2) NULL ,
"FEE_FREQ" NUMBER(11,2) NULL ,
"FEE_ELSE" NUMBER(11,2) NULL ,
"FEE_LATE" NUMBER(11,2) NULL ,
"FEE_BILL_CODE" VARCHAR2(40 BYTE) NULL ,
"FEE_OPERATION" VARCHAR2(40 BYTE) NOT NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_FEEURGENCYRECORD
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_FEEURGENCYRECORD";
CREATE TABLE "310000_STATDB"."RSBT_FEEURGENCYRECORD" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ORG_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"FEE_URGENCY_TIME" DATE NOT NULL ,
"FEE_YEAR" NUMBER NOT NULL ,
"FEE_BILL" NUMBER(11,2) NULL ,
"FEE_URGENCY_MODE" VARCHAR2(40 BYTE) NULL ,
"FEE_URGENCY_OPERATION" VARCHAR2(40 BYTE) NOT NULL ,
"FEE_URGENCY_PERSON" VARCHAR2(40 BYTE) NULL ,
"FEE_URGENCY_FILE_CODE" VARCHAR2(20 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_FREQ
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_FREQ";
CREATE TABLE "310000_STATDB"."RSBT_FREQ" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"STATION_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"FREQ_TYPE" VARCHAR2(1 BYTE) NULL ,
"FREQ_LC" NUMBER(14,7) NULL ,
"FREQ_UC" NUMBER(14,7) NULL ,
"FREQ_EFB" NUMBER(14,7) NULL ,
"FREQ_EFE" NUMBER(14,7) NULL ,
"FREQ_E_BAND" NUMBER(14,7) NULL ,
"FREQ_RFB" NUMBER(14,7) NULL ,
"FREQ_RFE" NUMBER(14,7) NULL ,
"FREQ_R_BAND" NUMBER(14,7) NULL ,
"FREQ_MOD" VARCHAR2(8 BYTE) NULL ,
"FREQ_MB" VARCHAR2(1 BYTE) NULL ,
"FREQ_CODE" VARCHAR2(36 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_FREQ_T
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_FREQ_T";
CREATE TABLE "310000_STATDB"."RSBT_FREQ_T" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"FT_FREQ_NO" VARCHAR2(2 BYTE) NULL ,
"FT_FREQ_TIMEB" DATE NULL ,
"FT_FREQ_TIMEE" DATE NULL ,
"FT_FREQ_INFO_TYPE" VARCHAR2(8 BYTE) NULL ,
"FT_FREQ_HCL" VARCHAR2(20 BYTE) NULL ,
"FT_FREQ_TYPE" VARCHAR2(1 BYTE) NULL ,
"FT_FREQ_MC" VARCHAR2(8 BYTE) NULL ,
"FT_FREQ_MC1" VARCHAR2(20 BYTE) NULL ,
"FT_FREQ_MC2" VARCHAR2(20 BYTE) NULL ,
"FT_FREQ_MC3" VARCHAR2(20 BYTE) NULL ,
"FT_FREQ_CCODE" VARCHAR2(20 BYTE) NULL ,
"FT_FREQ_CSGN" VARCHAR2(20 BYTE) NULL ,
"FT_FREQ_DUPDN" VARCHAR2(1 BYTE) NULL ,
"FT_FREQ_UNIT_TYPE" VARCHAR2(8 BYTE) NULL ,
"FT_FREQ_FEP" VARCHAR2(8 BYTE) NULL ,
"FT_FREQ_FRP" VARCHAR2(8 BYTE) NULL ,
"FT_FREQ_POWFLAG" VARCHAR2(8 BYTE) NULL ,
"FT_FREQ_EIRP" NUMBER(14,7) NULL ,
"FT_FREQ_POW_MAX" NUMBER(10,3) NULL ,
"FT_FREQ_POW_AVG" NUMBER(10,3) NULL ,
"FT_FREQ_EPOW" NUMBER(14,7) NULL ,
"FT_FREQ_TFCODE" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_LICENSE
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_LICENSE";
CREATE TABLE "310000_STATDB"."RSBT_LICENSE" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"STATION_GUID" VARCHAR2(36 BYTE) NULL ,
"APP_CODE" VARCHAR2(14 BYTE) NOT NULL ,
"STAT_TDI" VARCHAR2(4 BYTE) NOT NULL ,
"STAT_APP_TYPE" VARCHAR2(8 BYTE) NOT NULL ,
"LICENSE_TYPE" VARCHAR2(8 BYTE) NOT NULL ,
"LICENSE_CODE" VARCHAR2(30 BYTE) NULL ,
"LICENSE_ORG_NAME" VARCHAR2(60 BYTE) NULL ,
"LICENSE_MANAGER" VARCHAR2(60 BYTE) NULL ,
"LICENSE_DATE_B" DATE NULL ,
"LICENSE_DATE_E" DATE NULL ,
"LICENSE_DATE" DATE NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "310000_STATDB"."RSBT_LICENSE"."LICENSE_TYPE" IS '执照类型：0--B执照或小执照，1----A执照或大执照';

-- ----------------------------
-- Table structure for RSBT_LICENSE_T
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_LICENSE_T";
CREATE TABLE "310000_STATDB"."RSBT_LICENSE_T" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"LICENSE_STATUS" VARCHAR2(1 BYTE) NULL ,
"PRINT_STATUS" VARCHAR2(1 BYTE) NULL ,
"PRINT_TIME" DATE NULL ,
"RECORD_STATUS" VARCHAR2(1 BYTE) NULL ,
"USING_STATUS" VARCHAR2(1 BYTE) NULL ,
"STATE_DESCRIPTION" VARCHAR2(512 BYTE) NULL ,
"ANNUAL_STATUS" VARCHAR2(1 BYTE) NULL ,
"AUDIT_YEAR" VARCHAR2(4 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_LINK
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_LINK";
CREATE TABLE "310000_STATDB"."RSBT_LINK" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"NET_GUID_A" VARCHAR2(36 BYTE) NULL ,
"STATION_GUID_A" VARCHAR2(36 BYTE) NOT NULL ,
"GUID_EAF_A" VARCHAR2(36 BYTE) NULL ,
"NET_GUID_B" VARCHAR2(36 BYTE) NULL ,
"STATION_GUID_B" VARCHAR2(36 BYTE) NOT NULL ,
"GUID_EAF_B" VARCHAR2(36 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_NET
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_NET";
CREATE TABLE "310000_STATDB"."RSBT_NET" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ORG_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"FEE_GUID" VARCHAR2(36 BYTE) NULL ,
"ORG_CODE" VARCHAR2(9 BYTE) NOT NULL ,
"NET_NAME" VARCHAR2(80 BYTE) NULL ,
"NET_SVN" VARCHAR2(10 BYTE) NULL ,
"NET_SP" VARCHAR2(8 BYTE) NULL ,
"NET_TS" VARCHAR2(8 BYTE) NULL ,
"NET_BAND" NUMBER(14,7) NULL ,
"NET_AREA" VARCHAR2(8 BYTE) NULL ,
"NET_USE" VARCHAR2(80 BYTE) NULL ,
"NET_SAT_NAME" VARCHAR2(80 BYTE) NULL ,
"NET_LG" VARCHAR2(10 BYTE) NULL ,
"NET_START_DATE" DATE NULL ,
"NET_CONFIRM_DATE" DATE NULL ,
"NET_EXPIRED_DATE" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_ORG
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_ORG";
CREATE TABLE "310000_STATDB"."RSBT_ORG" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ORG_CODE" VARCHAR2(9 BYTE) DEFAULT 999999999  NOT NULL ,
"ORG_NAME" VARCHAR2(80 BYTE) NOT NULL ,
"ORG_AREA_CODE" VARCHAR2(8 BYTE) NOT NULL ,
"ORG_SYS_CODE" VARCHAR2(8 BYTE) NULL ,
"ORG_TYPE" VARCHAR2(3 BYTE) NOT NULL ,
"ORG_LINK_PERSON" VARCHAR2(40 BYTE) NULL ,
"ORG_PERSON_ID" VARCHAR2(40 BYTE) NULL ,
"ORG_SUP_CODE" VARCHAR2(9 BYTE) NULL ,
"ORG_ADDR" VARCHAR2(80 BYTE) NULL ,
"ORG_POST" VARCHAR2(6 BYTE) NULL ,
"ORG_PHONE" VARCHAR2(40 BYTE) NULL ,
"ORG_MOB_PHONE" VARCHAR2(40 BYTE) NULL ,
"ORG_FAX" VARCHAR2(40 BYTE) NULL ,
"ORG_BANK" VARCHAR2(80 BYTE) NULL ,
"ORG_ACCOUNT_NAME" VARCHAR2(80 BYTE) NULL ,
"ORG_ACCOUNT" VARCHAR2(40 BYTE) NULL ,
"ORG_HOSTILITY" NUMBER(1) NULL ,
"ORG_WEB_SITE" VARCHAR2(80 BYTE) NULL ,
"ORG_MAIL" VARCHAR2(80 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_ST_COBJ
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_ST_COBJ";
CREATE TABLE "310000_STATDB"."RSBT_ST_COBJ" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"STATION_GUID" VARCHAR2(36 BYTE) NOT NULL ,
"OBJ_TYPE" VARCHAR2(1 BYTE) NOT NULL ,
"OBJ_NAME" VARCHAR2(80 BYTE) NOT NULL ,
"OBJ_TDI" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_STATION
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_STATION";
CREATE TABLE "310000_STATDB"."RSBT_STATION" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"NET_GUID" VARCHAR2(36 BYTE) NULL ,
"ORG_CODE" VARCHAR2(9 BYTE) NOT NULL ,
"APP_CODE" VARCHAR2(14 BYTE) NOT NULL ,
"STAT_APP_TYPE" VARCHAR2(8 BYTE) NOT NULL ,
"STAT_TDI" VARCHAR2(4 BYTE) NOT NULL ,
"STAT_NAME" VARCHAR2(80 BYTE) NULL ,
"STAT_ADDR" VARCHAR2(80 BYTE) NULL ,
"STAT_AREA_CODE" VARCHAR2(8 BYTE) NULL ,
"STAT_TYPE" VARCHAR2(8 BYTE) NULL ,
"STAT_WORK" VARCHAR2(8 BYTE) NULL ,
"STAT_STATUS" VARCHAR2(8 BYTE) NULL ,
"STAT_EQU_SUM" NUMBER(7) NULL ,
"STAT_LG" NUMBER(10,7) NULL ,
"STAT_LA" NUMBER(10,7) NULL ,
"STAT_AT" NUMBER(6,2) NULL ,
"STAT_DATE_START" DATE NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL ,
"STAT_COODINATION" VARCHAR2(8 BYTE) NULL ,
"STAT_INTCOORDSTATUS" VARCHAR2(8 BYTE) NULL ,
"STAT_INTCOODINATION" VARCHAR2(8 BYTE) NULL ,
"STAT_COORDADM" VARCHAR2(80 BYTE) NULL ,
"STAT_REGISTERCODE" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_STATION_T
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_STATION_T";
CREATE TABLE "310000_STATDB"."RSBT_STATION_T" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"ST_TIME_B" DATE NULL ,
"ST_TIME_E" DATE NULL ,
"ST_LMMTR" VARCHAR2(1 BYTE) NULL ,
"ST_USER_AREA" VARCHAR2(80 BYTE) NULL ,
"ST_TF_CODE" VARCHAR2(40 BYTE) NULL ,
"ST_TF_TRANS_CA_PU" VARCHAR2(8 BYTE) NULL ,
"ST_TF_TRANS_CA_P" NUMBER(14,7) NULL ,
"ST_E_NET_CODE" VARCHAR2(20 BYTE) NULL ,
"ST_E_MULTI_ADDR" VARCHAR2(8 BYTE) NULL ,
"ST_E_COM_AREA" VARCHAR2(8 BYTE) NULL ,
"ST_POS_TYPE" VARCHAR2(8 BYTE) NULL ,
"ST_E_POS" VARCHAR2(40 BYTE) NULL ,
"ST_E_SAT" VARCHAR2(40 BYTE) NULL ,
"ST_E_LG" VARCHAR2(20 BYTE) NULL ,
"ST_B_SGN" VARCHAR2(40 BYTE) NULL ,
"ST_B_LEVEL" VARCHAR2(8 BYTE) NULL ,
"ST_B_BM" VARCHAR2(8 BYTE) NULL ,
"ST_B_EDU" VARCHAR2(1 BYTE) NULL ,
"ST_B_IC" VARCHAR2(1 BYTE) NULL ,
"ST_B_COVER_AREA" VARCHAR2(40 BYTE) NULL ,
"ST_SHIP_TYPE" VARCHAR2(8 BYTE) NULL ,
"ST_CALL_SIGN" VARCHAR2(20 BYTE) NULL ,
"ST_S_MMSI" VARCHAR2(20 BYTE) NULL ,
"ST_S_CS" VARCHAR2(20 BYTE) NULL ,
"ST_SHIP_NAME" VARCHAR2(80 BYTE) NULL ,
"ST_S_PN" VARCHAR2(80 BYTE) NULL ,
"ST_S_AAIC" VARCHAR2(20 BYTE) NULL ,
"ST_S_T" NUMBER(10,2) NULL ,
"ST_S_P" NUMBER(10,2) NULL ,
"ST_A_MODEL" VARCHAR2(40 BYTE) NULL ,
"ST_A_TYPE" VARCHAR2(8 BYTE) NULL ,
"ST_A_CALL" VARCHAR2(1 BYTE) NULL ,
"ST_A_CALL_OI" VARCHAR2(20 BYTE) NULL ,
"ST_A_SGN" VARCHAR2(20 BYTE) NULL ,
"ST_A_ST" NUMBER(10,2) NULL ,
"ST_A_PILOTING" VARCHAR2(1 BYTE) NULL ,
"ST_A_NRM" VARCHAR2(40 BYTE) NULL ,
"ST_R_WAMIN" VARCHAR2(20 BYTE) NULL ,
"ST_R_WAMAX" VARCHAR2(20 BYTE) NULL ,
"ST_R_EMIN" VARCHAR2(20 BYTE) NULL ,
"ST_R_EMAX" VARCHAR2(20 BYTE) NULL ,
"ST_C_CODE" VARCHAR2(40 BYTE) NULL ,
"ST_C_SUM" NUMBER(3) NULL ,
"ST_SERV_R" NUMBER(10,3) NULL ,
"ST_D_TEC_TYPE" VARCHAR2(20 BYTE) NULL ,
"ST_D_TYPE" VARCHAR2(1 BYTE) NULL ,
"ST_ME_SAT_NAME" VARCHAR2(80 BYTE) NULL ,
"ST_ME_STA1" VARCHAR2(80 BYTE) NULL ,
"ST_ME_STA2" VARCHAR2(80 BYTE) NULL ,
"ST_ME_STA3" VARCHAR2(80 BYTE) NULL ,
"ST_ME_STYPE" VARCHAR2(1 BYTE) NULL ,
"ST_ME_NAME1" VARCHAR2(80 BYTE) NULL ,
"ST_ME_NAME2" VARCHAR2(80 BYTE) NULL ,
"ST_ME_LG1" NUMBER(10,7) NULL ,
"ST_ME_LG2" NUMBER(10,7) NULL ,
"ST_ME_FBAND" NUMBER(14,7) NULL ,
"ST_B_TYPE1" VARCHAR2(8 BYTE) NULL ,
"ST_B_TYPE2" VARCHAR2(8 BYTE) NULL ,
"ST_ME_FILE_NO" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_STATIONILLEGALRECORD
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_STATIONILLEGALRECORD";
CREATE TABLE "310000_STATDB"."RSBT_STATIONILLEGALRECORD" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"STATION_GUID" VARCHAR2(36 BYTE) NULL ,
"STATION_ILLEGAL_TIME" DATE NOT NULL ,
"STATION_ILLEGAL_MODE" VARCHAR2(8 BYTE) NULL ,
"STATION_ILLEGAL_DATE" NUMBER(12,5) NULL ,
"STATION_ILLEGAL_DATE_U" VARCHAR2(8 BYTE) NULL ,
"STATION_ILLEGAL_LG" NUMBER(10,7) NULL ,
"STATION_ILLEGAL_LA" NUMBER(10,7) NULL ,
"STATION_ILLEGAL_EQUMODE" VARCHAR2(40 BYTE) NULL ,
"STATION_PUNISH_TIME" DATE NOT NULL ,
"STATION_PUNISH_RESULT" VARCHAR2(80 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for RSBT_STATIONSUPERVISIONRECORD
-- ----------------------------
DROP TABLE "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD";
CREATE TABLE "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD" (
"GUID" VARCHAR2(36 BYTE) NOT NULL ,
"STATION_GUID" VARCHAR2(36 BYTE) NULL ,
"STATION_ILLEGAL_TIME" DATE NOT NULL ,
"STATION_ILLEGAL_MODE" VARCHAR2(8 BYTE) NULL ,
"STATION_SUPERVISION_STATUS" VARCHAR2(8 BYTE) NULL ,
"STATION_ILLEGAL_DATE" NUMBER(12,5) NULL ,
"STATION_ILLEGAL_DATE_U" VARCHAR2(8 BYTE) NULL ,
"STATION_ILLEGAL_LG" NUMBER(10,7) NULL ,
"STATION_ILLEGAL_LA" NUMBER(10,7) NULL ,
"STATION_ILLEGAL_EQUMODE" VARCHAR2(40 BYTE) NULL ,
"STATION_PUNISH_TIME" DATE NOT NULL ,
"STATION_PUNISH_RESULT" VARCHAR2(80 BYTE) NULL ,
"MEMO" VARCHAR2(512 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD" IS '无线电台站监管记录表';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."GUID" IS '主键';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_GUID" IS 'RSBT_ STATION';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_ILLEGAL_TIME" IS '台站违规及受干扰时间';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_ILLEGAL_MODE" IS '台站违规及受干扰类别';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_SUPERVISION_STATUS" IS '台站监管状态';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_ILLEGAL_DATE" IS '台站违规参数';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_ILLEGAL_DATE_U" IS '违规参数单位';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_ILLEGAL_LG" IS '违规台站经度';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_ILLEGAL_LA" IS '违规台站纬度';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_ILLEGAL_EQUMODE" IS '违规设备型号';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_PUNISH_TIME" IS '违规查处时间';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."STATION_PUNISH_RESULT" IS '违规查处结果';
COMMENT ON COLUMN "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"."MEMO" IS '备注';

-- ----------------------------
-- Indexes structure for table RSBT_ANTFEED
-- ----------------------------
CREATE INDEX "310000_STATDB"."I_RSBT_ANTFEED"
ON "310000_STATDB"."RSBT_ANTFEED" ("STATION_GUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table RSBT_ANTFEED
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ANTFEED" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_ANTFEED" ADD CHECK ("STATION_GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_ANTFEED
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ANTFEED" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_ANTFEED_T
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_ANTFEED_T
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ANTFEED_T" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_ANTFEED_T
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ANTFEED_T" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_APPCLUBS
-- ----------------------------

-- ----------------------------
-- Triggers structure for table RSBT_APPCLUBS
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_APPCLUBS_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_APPCLUBS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_appclubs','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_appclubs','DELETE', sysdate);
END tri_rsbt_appclubs_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_APPCLUBS_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_APPCLUBS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_appclubs','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_appclubs','INSERT', sysdate);
END tri_rsbt_appclubs_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_APPCLUBS_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_APPCLUBS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_appclubs','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_appclubs','UPDATE', sysdate);
END tri_rsbt_appclubs_update;



-- ----------------------------
-- Checks structure for table RSBT_APPCLUBS
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPCLUBS" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPCLUBS" ADD CHECK ("APP_GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_APPCLUBS
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPCLUBS" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_APPFILELIST
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_APPFILELIST
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPFILELIST" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPFILELIST" ADD CHECK ("APP_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPFILELIST" ADD CHECK ("APP_CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_APPFILELIST
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPFILELIST" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_APPFREQ
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_APPFREQ
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPFREQ" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPFREQ" ADD CHECK ("APP_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPFREQ" ADD CHECK ("APP_CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_APPFREQ
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPFREQ" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_APPLY
-- ----------------------------
CREATE INDEX "310000_STATDB"."I_RSBT_APPLY_APP_CODE"
ON "310000_STATDB"."RSBT_APPLY" ("APP_CODE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table RSBT_APPLY
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD CHECK ("NET_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD CHECK ("ORG_MANAGER_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD CHECK ("APP_CODE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD CHECK ("APP_TYPE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD CHECK ("APP_SUB_TYPE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD CHECK ("APP_OBJECT_TYPE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD CHECK ("APP_FTLB" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD CHECK ("APP_FTLE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_APPLY
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_APPLY_PA
-- ----------------------------

-- ----------------------------
-- Triggers structure for table RSBT_APPLY_PA
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_APPLY_PA_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_APPLY_PA" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_apply_pa','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_apply_pa','DELETE', sysdate);
END tri_rsbt_apply_pa_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_APPLY_PA_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_APPLY_PA" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_apply_pa','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_apply_pa','INSERT', sysdate);
END tri_rsbt_apply_pa_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_APPLY_PA_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_APPLY_PA" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_apply_pa','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_apply_pa','UPDATE', sysdate);
END tri_rsbt_apply_pa_update;



-- ----------------------------
-- Checks structure for table RSBT_APPLY_PA
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPLY_PA" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY_PA" ADD CHECK ("APP_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY_PA" ADD CHECK ("APP_PA_NAME" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY_PA" ADD CHECK ("APP_PA_GENDER" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY_PA" ADD CHECK ("APP_PA_BIRTHDAY" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY_PA" ADD CHECK ("APP_PA_NATION" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY_PA" ADD CHECK ("APP_PA_DEGREE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_APPLY_PA" ADD CHECK ("APP_PA_ID_CARD" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_APPLY_PA
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPLY_PA" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_CODE_DIC
-- ----------------------------
CREATE INDEX "310000_STATDB"."I_RSBT_CODE_DIC"
ON "310000_STATDB"."RSBT_CODE_DIC" ("CN" ASC, "CODE_DATA_TYPE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Triggers structure for table RSBT_CODE_DIC
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_CODE_DIC_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_CODE_DIC" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.co,'rsbt_code_dic','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.co,'rsbt_code_dic','DELETE', sysdate);
END tri_rsbt_code_dic_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_CODE_DIC_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_CODE_DIC" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.co,'rsbt_code_dic','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.co,'rsbt_code_dic','INSERT', sysdate);
END tri_rsbt_code_dic_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_CODE_DIC_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_CODE_DIC" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.co,'rsbt_code_dic','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.co,'rsbt_code_dic','UPDATE', sysdate);
END tri_rsbt_code_dic_update;



-- ----------------------------
-- Checks structure for table RSBT_CODE_DIC
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_CODE_DIC" ADD CHECK ("CO" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_CODE_DIC" ADD CHECK ("CN" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_CODE_DIC" ADD CHECK ("CODE_DISCN" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_CODE_DIC
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_CODE_DIC" ADD PRIMARY KEY ("CO");

-- ----------------------------
-- Checks structure for table RSBT_DB_POOL
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_DB_POOL" ADD CHECK ("ORG_AREA_CODE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_DB_POOL" ADD CHECK ("DATABASE_MANAGEMENT_USER" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_DB_POOL" ADD CHECK ("DATABASE_PASSWORD" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table RSBT_E_SE
-- ----------------------------

-- ----------------------------
-- Triggers structure for table RSBT_E_SE
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_E_SE_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_E_SE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_e_se','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_e_se','DELETE', sysdate);
END tri_rsbt_e_se_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_E_SE_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_E_SE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_e_se','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_e_se','INSERT', sysdate);
END tri_rsbt_e_se_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_E_SE_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_E_SE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_e_se','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_e_se','UPDATE', sysdate);
END tri_rsbt_e_se_update;



-- ----------------------------
-- Checks structure for table RSBT_E_SE
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_E_SE" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_E_SE" ADD CHECK ("STATION_GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_E_SE
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_E_SE" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_EAF
-- ----------------------------
CREATE INDEX "310000_STATDB"."I_RSBT_EAF_FREQ"
ON "310000_STATDB"."RSBT_EAF" ("FREQ_GUID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "310000_STATDB"."I_RSBT_EAF_STATIONGUID"
ON "310000_STATDB"."RSBT_EAF" ("STATION_GUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table RSBT_EAF
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_EAF" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_EAF" ADD CHECK ("STATION_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_EAF" ADD CHECK ("EQU_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_EAF" ADD CHECK ("ANT_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_EAF" ADD CHECK ("FREQ_GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_EAF
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_EAF" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_EQU
-- ----------------------------
CREATE INDEX "310000_STATDB"."I_RSBT_EQU"
ON "310000_STATDB"."RSBT_EQU" ("STATION_GUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table RSBT_EQU
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_EQU" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_EQU" ADD CHECK ("STATION_GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_EQU
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_EQU" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_EQU_T
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_EQU_T
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_EQU_T" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_EQU_T
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_EQU_T" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_FEE_DERATE
-- ----------------------------

-- ----------------------------
-- Triggers structure for table RSBT_FEE_DERATE
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEE_DERATE_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_FEE_DERATE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_fee_derate','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_fee_derate','DELETE', sysdate);
END tri_rsbt_fee_derate_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEE_DERATE_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_FEE_DERATE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_fee_derate','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_fee_derate','INSERT', sysdate);
END tri_rsbt_fee_derate_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEE_DERATE_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_FEE_DERATE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_fee_derate','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_fee_derate','UPDATE', sysdate);
END tri_rsbt_fee_derate_update;



-- ----------------------------
-- Checks structure for table RSBT_FEE_DERATE
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEE_DERATE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEE_DERATE" ADD CHECK ("PROPORTION" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_FEE_DERATE
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEE_DERATE" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_FEEEVERYYEAR
-- ----------------------------
CREATE INDEX "310000_STATDB"."I_RSBT_FEEEYEARSTATIOGUID"
ON "310000_STATDB"."RSBT_FEEEVERYYEAR" ("STATION_GUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Triggers structure for table RSBT_FEEEVERYYEAR
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEEEVERYYEAR_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_FEEEVERYYEAR" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeeveryyear','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeeveryyear','DELETE', sysdate);
END tri_rsbt_feeeveryyear_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEEEVERYYEAR_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_FEEEVERYYEAR" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_feeeveryyear','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_feeeveryyear','INSERT', sysdate);
END tri_rsbt_feeeveryyear_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEEEVERYYEAR_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_FEEEVERYYEAR" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeeveryyear','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeeveryyear','UPDATE', sysdate);
END tri_rsbt_feeeveryyear_update;



-- ----------------------------
-- Checks structure for table RSBT_FEEEVERYYEAR
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD CHECK ("ORG_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD CHECK ("FEE_TYPE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD CHECK ("FEE_SUM" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD CHECK ("FEE_PAY_MONTH" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD CHECK ("FEE_OPERATION" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD CHECK ("FEE_OPERATION_DATE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_FEEEVERYYEAR
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_FEERECORD
-- ----------------------------

-- ----------------------------
-- Triggers structure for table RSBT_FEERECORD
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEERECORD_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_FEERECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feerecord','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feerecord','DELETE', sysdate);
END tri_rsbt_feerecord_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEERECORD_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_FEERECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_feerecord','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_feerecord','INSERT', sysdate);
END tri_rsbt_feerecord_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEERECORD_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_FEERECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feerecord','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feerecord','UPDATE', sysdate);
END tri_rsbt_feerecord_update;



-- ----------------------------
-- Checks structure for table RSBT_FEERECORD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEERECORD" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEERECORD" ADD CHECK ("FEE_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEERECORD" ADD CHECK ("FEE_TIME" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEERECORD" ADD CHECK ("FEE_YEAR" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEERECORD" ADD CHECK ("FEE_SUM" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_FEERECORD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEERECORD" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_FEESTANDERD
-- ----------------------------

-- ----------------------------
-- Triggers structure for table RSBT_FEESTANDERD
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEESTANDERD_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_FEESTANDERD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.ITEM_CODE,'rsbt_feestanderd','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.ITEM_CODE,'rsbt_feestanderd','DELETE', sysdate);
END tri_rsbt_feestanderd_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEESTANDERD_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_FEESTANDERD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.ITEM_CODE,'rsbt_feestanderd','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.ITEM_CODE,'rsbt_feestanderd','INSERT', sysdate);
END tri_rsbt_feestanderd_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEESTANDERD_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_FEESTANDERD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.ITEM_CODE,'rsbt_feestanderd','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.ITEM_CODE,'rsbt_feestanderd','UPDATE', sysdate);
END tri_rsbt_feestanderd_update;



-- ----------------------------
-- Checks structure for table RSBT_FEESTANDERD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEESTANDERD" ADD CHECK ("ITEM_CODE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEESTANDERD" ADD CHECK ("ITEM_NAME" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEESTANDERD" ADD CHECK ("ITEM_TYPE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEESTANDERD" ADD CHECK ("TYPE_NAME" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEESTANDERD" ADD CHECK ("FEE_PAY" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEESTANDERD" ADD CHECK ("COUNT_MODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_FEESTANDERD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEESTANDERD" ADD PRIMARY KEY ("ITEM_CODE");

-- ----------------------------
-- Indexes structure for table RSBT_FEEUNITRECORD
-- ----------------------------

-- ----------------------------
-- Triggers structure for table RSBT_FEEUNITRECORD
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEEUNITRECORD_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_FEEUNITRECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeunitrecord','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeunitrecord','DELETE', sysdate);
END tri_rsbt_feeunitrecord_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEEUNITRECORD_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_FEEUNITRECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_feeunitrecord','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_feeunitrecord','INSERT', sysdate);
END tri_rsbt_feeunitrecord_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEEUNITRECORD_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_FEEUNITRECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeunitrecord','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeunitrecord','UPDATE', sysdate);
END tri_rsbt_feeunitrecord_update;



-- ----------------------------
-- Checks structure for table RSBT_FEEUNITRECORD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEEUNITRECORD" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEUNITRECORD" ADD CHECK ("ORG_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEUNITRECORD" ADD CHECK ("FEE_TIME" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEUNITRECORD" ADD CHECK ("FEE_YEAR" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEUNITRECORD" ADD CHECK ("FEE_OPERATION" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_FEEUNITRECORD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEEUNITRECORD" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_FEEURGENCYRECORD
-- ----------------------------

-- ----------------------------
-- Triggers structure for table RSBT_FEEURGENCYRECORD
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEEURRECORD_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_FEEURGENCYRECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeurgencyrecord','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeurgencyrecord','DELETE', sysdate);
END tri_rsbt_feeurrecord_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEEURRECORD_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_FEEURGENCYRECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_feeurgencyrecord','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_feeurgencyrecord','INSERT', sysdate);
END tri_rsbt_feeurrecord_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_FEEURRECORD_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_FEEURGENCYRECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeurgencyrecord','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_feeurgencyrecord','UPDATE', sysdate);
END tri_rsbt_feeurrecord_update;



-- ----------------------------
-- Checks structure for table RSBT_FEEURGENCYRECORD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEEURGENCYRECORD" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEURGENCYRECORD" ADD CHECK ("ORG_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEURGENCYRECORD" ADD CHECK ("FEE_URGENCY_TIME" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEURGENCYRECORD" ADD CHECK ("FEE_YEAR" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FEEURGENCYRECORD" ADD CHECK ("FEE_URGENCY_OPERATION" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_FEEURGENCYRECORD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEEURGENCYRECORD" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_FREQ
-- ----------------------------
CREATE INDEX "310000_STATDB"."I_RSBT_FREQ"
ON "310000_STATDB"."RSBT_FREQ" ("STATION_GUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table RSBT_FREQ
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FREQ" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_FREQ" ADD CHECK ("STATION_GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_FREQ
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FREQ" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_FREQ_T
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_FREQ_T
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FREQ_T" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_FREQ_T
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FREQ_T" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_LICENSE
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_LICENSE
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_LICENSE" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_LICENSE" ADD CHECK ("APP_CODE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_LICENSE" ADD CHECK ("STAT_TDI" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_LICENSE" ADD CHECK ("STAT_APP_TYPE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_LICENSE" ADD CHECK ("LICENSE_TYPE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_LICENSE
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_LICENSE" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_LICENSE_T
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table RSBT_LICENSE_T
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_LICENSE_T" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_LINK
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_LINK
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_LINK" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_LINK" ADD CHECK ("STATION_GUID_A" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_LINK" ADD CHECK ("STATION_GUID_B" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_LINK
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_LINK" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_NET
-- ----------------------------
CREATE INDEX "310000_STATDB"."I_RSBT_NET"
ON "310000_STATDB"."RSBT_NET" ("ORG_GUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table RSBT_NET
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_NET" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_NET" ADD CHECK ("ORG_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_NET" ADD CHECK ("ORG_CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_NET
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_NET" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_ORG
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_ORG
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ORG" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_ORG" ADD CHECK ("ORG_CODE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_ORG" ADD CHECK ("ORG_NAME" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_ORG" ADD CHECK ("ORG_AREA_CODE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_ORG" ADD CHECK ("ORG_TYPE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_ORG
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ORG" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_ST_COBJ
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_ST_COBJ
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ST_COBJ" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_ST_COBJ" ADD CHECK ("STATION_GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_ST_COBJ" ADD CHECK ("OBJ_TYPE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_ST_COBJ" ADD CHECK ("OBJ_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_ST_COBJ
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ST_COBJ" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_STATION
-- ----------------------------
CREATE INDEX "310000_STATDB"."I_RSBT_STATION_APPCODE"
ON "310000_STATDB"."RSBT_STATION" ("APP_CODE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "310000_STATDB"."I_RSBT_STATION_NET"
ON "310000_STATDB"."RSBT_STATION" ("NET_GUID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "310000_STATDB"."I_RSDB_STATION"
ON "310000_STATDB"."RSBT_STATION" ("STAT_APP_TYPE" ASC, "GUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table RSBT_STATION
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATION" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_STATION" ADD CHECK ("ORG_CODE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_STATION" ADD CHECK ("APP_CODE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_STATION" ADD CHECK ("STAT_APP_TYPE" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_STATION" ADD CHECK ("STAT_TDI" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_STATION
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATION" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_STATION_T
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_STATION_T
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATION_T" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_STATION_T
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATION_T" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_STATIONILLEGALRECORD
-- ----------------------------

-- ----------------------------
-- Triggers structure for table RSBT_STATIONILLEGALRECORD
-- ----------------------------
CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_RECORD_DELETE" AFTER DELETE ON "310000_STATDB"."RSBT_STATIONILLEGALRECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_stationillegalrecord','DELETE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_stationillegalrecord','DELETE', sysdate);
END tri_rsbt_record_delete;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_RECORD_INSERT" AFTER INSERT ON "310000_STATDB"."RSBT_STATIONILLEGALRECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_stationillegalrecord','INSERT', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:NEW.guid,'rsbt_stationillegalrecord','INSERT', sysdate);
END tri_rsbt_record_insert;


CREATE OR REPLACE TRIGGER "310000_STATDB"."TRI_RSBT_RECORD_UPDATE" AFTER UPDATE ON "310000_STATDB"."RSBT_STATIONILLEGALRECORD" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
DECLARE
 BEGIN
    INSERT INTO data_operate_log (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_stationillegalrecord','UPDATE', sysdate);
    INSERT INTO data_operate_log_bak (GUID,TABLENAME,OPERATE_TYPE,OPERATE_DATE) VALUES(:OLD.guid,'rsbt_stationillegalrecord','UPDATE', sysdate);
END tri_rsbt_record_update;



-- ----------------------------
-- Checks structure for table RSBT_STATIONILLEGALRECORD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATIONILLEGALRECORD" ADD CHECK ("STATION_ILLEGAL_TIME" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_STATIONILLEGALRECORD" ADD CHECK ("STATION_PUNISH_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_STATIONILLEGALRECORD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATIONILLEGALRECORD" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table RSBT_STATIONSUPERVISIONRECORD
-- ----------------------------

-- ----------------------------
-- Checks structure for table RSBT_STATIONSUPERVISIONRECORD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD" ADD CHECK ("STATION_ILLEGAL_TIME" IS NOT NULL);
ALTER TABLE "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD" ADD CHECK ("STATION_PUNISH_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RSBT_STATIONSUPERVISIONRECORD
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_ANTFEED"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ANTFEED" ADD FOREIGN KEY ("STATION_GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_ANTFEED_T"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ANTFEED_T" ADD FOREIGN KEY ("GUID") REFERENCES "310000_STATDB"."RSBT_ANTFEED" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_APPCLUBS"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPCLUBS" ADD FOREIGN KEY ("APP_GUID") REFERENCES "310000_STATDB"."RSBT_APPLY_PA" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_APPFILELIST"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPFILELIST" ADD FOREIGN KEY ("APP_GUID") REFERENCES "310000_STATDB"."RSBT_APPLY" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_APPFREQ"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPFREQ" ADD FOREIGN KEY ("APP_GUID") REFERENCES "310000_STATDB"."RSBT_APPLY" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_APPLY"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD FOREIGN KEY ("ORG_GUID") REFERENCES "310000_STATDB"."RSBT_ORG" ("GUID");
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD FOREIGN KEY ("NET_GUID") REFERENCES "310000_STATDB"."RSBT_NET" ("GUID");
ALTER TABLE "310000_STATDB"."RSBT_APPLY" ADD FOREIGN KEY ("ORG_MANAGER_GUID") REFERENCES "310000_STATDB"."RSBT_ORG" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_APPLY_PA"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_APPLY_PA" ADD FOREIGN KEY ("APP_GUID") REFERENCES "310000_STATDB"."RSBT_APPLY" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_E_SE"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_E_SE" ADD FOREIGN KEY ("STATION_GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_EAF"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_EAF" ADD FOREIGN KEY ("STATION_GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_EQU"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_EQU" ADD FOREIGN KEY ("STATION_GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_EQU_T"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_EQU_T" ADD FOREIGN KEY ("GUID") REFERENCES "310000_STATDB"."RSBT_EQU" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_FEEEVERYYEAR"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD FOREIGN KEY ("ORG_GUID") REFERENCES "310000_STATDB"."RSBT_ORG" ("GUID");
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD FOREIGN KEY ("NET_GUID") REFERENCES "310000_STATDB"."RSBT_NET" ("GUID");
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD FOREIGN KEY ("STATION_GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID");
ALTER TABLE "310000_STATDB"."RSBT_FEEEVERYYEAR" ADD FOREIGN KEY ("FEE_DERATE_ACCORDING") REFERENCES "310000_STATDB"."RSBT_FEE_DERATE" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_FEERECORD"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEERECORD" ADD FOREIGN KEY ("FEE_GUID") REFERENCES "310000_STATDB"."RSBT_FEEEVERYYEAR" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_FEEUNITRECORD"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEEUNITRECORD" ADD FOREIGN KEY ("ORG_GUID") REFERENCES "310000_STATDB"."RSBT_ORG" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_FEEURGENCYRECORD"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FEEURGENCYRECORD" ADD FOREIGN KEY ("ORG_GUID") REFERENCES "310000_STATDB"."RSBT_ORG" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_FREQ"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FREQ" ADD FOREIGN KEY ("STATION_GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_FREQ_T"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_FREQ_T" ADD FOREIGN KEY ("GUID") REFERENCES "310000_STATDB"."RSBT_FREQ" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_LICENSE"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_LICENSE" ADD FOREIGN KEY ("STATION_GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_LICENSE_T"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_LICENSE_T" ADD FOREIGN KEY ("GUID") REFERENCES "310000_STATDB"."RSBT_LICENSE" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_LINK"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_LINK" ADD FOREIGN KEY ("STATION_GUID_A") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID") ON DELETE CASCADE;
ALTER TABLE "310000_STATDB"."RSBT_LINK" ADD FOREIGN KEY ("STATION_GUID_B") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_NET"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_NET" ADD FOREIGN KEY ("ORG_GUID") REFERENCES "310000_STATDB"."RSBT_ORG" ("GUID");
ALTER TABLE "310000_STATDB"."RSBT_NET" ADD FOREIGN KEY ("FEE_GUID") REFERENCES "310000_STATDB"."RSBT_ORG" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_ST_COBJ"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_ST_COBJ" ADD FOREIGN KEY ("STATION_GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_STATION"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATION" ADD FOREIGN KEY ("NET_GUID") REFERENCES "310000_STATDB"."RSBT_NET" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_STATION_T"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATION_T" ADD FOREIGN KEY ("GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID") ON DELETE CASCADE;

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_STATIONILLEGALRECORD"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATIONILLEGALRECORD" ADD FOREIGN KEY ("STATION_GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID");

-- ----------------------------
-- Foreign Key structure for table "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD"
-- ----------------------------
ALTER TABLE "310000_STATDB"."RSBT_STATIONSUPERVISIONRECORD" ADD FOREIGN KEY ("STATION_GUID") REFERENCES "310000_STATDB"."RSBT_STATION" ("GUID");
