

CREATE TABLE APP_ACT_NOTIFICATION_CFG(ID char(36) NOT NULL,ISCLOSE char(1),ISSTORE char(1),PRIMARY KEY (ID));
CREATE TABLE APP_ACT_NOTIFICATION_MSG( ID char(36) NOT NULL, REGISTERID varchar2(128), APPID varchar2(64), OWNERID varchar2(36), TARGETID varchar2(36), NOTIFYCONTENT clob, NOTIFYLEVEL char(1), ISCLOSE char(1), CREATETIME date, ISSTORE char(1), READTIME date, READED char(1), PRIMARY KEY (ID));

